### ISSUE TITLE
[filter-effects] Are blur parameters to drop-shadow() specifying a "blur radius" or a standard deviation

### ISSUE THREAD

**Issue by fsoder** [w3c/fxtf-drafts#102]
The section defining the `drop-shadow()` function [1] states that

> Values are interpreted as for box-shadow [CSS3BG].

which would seem to imply that the blur parameter is a "blur radius". However it also references [2] as a supposedly equivalent description using the `<feDropShadow>` element, suggesting that the blur parameter would be specified as a standard deviation. One of these references ought to be incorrect.

[1] https://drafts.fxtf.org/filters/#funcdef-filter-drop-shadow
[2] https://drafts.fxtf.org/filters/#dropshadowEquivalent

**Comment by longsonr** [comment]
The blur parameter should be the same as for feDropShadow and the same as for feGaussianBlur, anything else would be inconsistent and for feGaussianBlur not backwards compatible so I think the specification text needs to change not to mention box-shadow.

**Comment by smfr** [comment]
Agreed; drop-shadow() should match SVG, not box-shadow (see the bottom of https://dbaron.org/log/20110225-blur-radius).

**Comment by AmeliaBR** [comment]
Has anyone tested what browsers are doing?

I'm pretty sure that authors are going to expect `drop-shadow(0 0 5px blue)` to behave like `box-shadow: 0 0 5px blue`.

**Comment by fsoder** [comment]
If what I wrote in [1] is true, Blink and Gecko have it as a standard deviation, and based on the reporters statement WebKit/Safari interpret it like box-shadow. Author expectation is the latter based on that bug.

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=677689

**Comment by dirkschulze** [comment]
I created an example: https://codepen.io/anon/pen/pwjYOQ

Safari, Chrome and Firefox treat the value of box-shadow and drop-shadow as standard deviation. At this point I don't think it is reasonable to change this. Especially since the filter properties are un-prefixed. I will change the spec text to be more clear and add a note that this is different to `box-shadow`.

**Comment by AmeliaBR** [comment]
Confirm that Edge does the same.  Safari must have changed their implementation to match (or maybe treats `-webkit-filter` differently from `filter`).

So I agree that the spec might as well be consistent with implementations, but we'll need a clear definition of the properties in this spec, and a warning that they don't match box/text-shadow.
