### ISSUE TITLE
[motion] Define offset-rotate at sharp path segment boundaries

### ISSUE THREAD

**Issue by karip** [w3c/fxtf-drafts#108]
The [Motion Path Level 1 offset-rotate](https://drafts.fxtf.org/motion-1/#offset-rotate-property) should say what is the rotation at sharp path segment boundaries. I suggest that the direction of the end of the previous segment is used. Google Chrome seems to implement this, as shown by this example: https://jsfiddle.net/e371jukL/1/

Note that the orientation isn’t the average between incoming and outgoing tangents. It would cause annoying flickering in animations, because it would be displayed only for one frame.

**Comment by jihyerish** [comment]
Thanks for your feedback @karip !
