### ISSUE TITLE
[filter-effects] Clarify feTurbulence description regarding alpha channel

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/fxtf-drafts#112]
Browsers are currently inconsistent about what they return for a `<feTurbulence>` filter with no turbulence (i.e., with the default `baseFrequency="0").

- Chrome and MS Edge return a fully transparent layer when `type="turbulence"` but a half-transparent gray layer when `type="fractalNoise"`.
- Firefox returns a fully transparent layer in both cases.

[See CodePen test case](http://codepen.io/AmeliaBR/pen/zZxozG/)

I assume this is related to the fact that the `turbulence` algorithm returns values from 0 to 1, but the `fractalNoise` algorithm returns values from -1 to +1. In both cases, the results are then supposed to be scaled to the range of the color channel.  But [the spec text](https://drafts.fxtf.org/filters/#feTurbulenceElement) doesn't specifically say anything about the alpha channel. 

I'm leaning towards just calling this a Firefox bug, but I haven't actually deconstructed the algorithms to confirm that this is so. And either way, the spec text about scaling by 255 to get a color value should be clarified to encompass the alpha channel.

**Comment by Ani-Mayhem-Com** [comment]
Firefox is in error. I tested baseFrequency="0" in the JS implementation I made for testing the seed bug. I get a fully transparent layer, and a half-transparent gray layer.

**Comment by AmeliaBR** [comment]
Thanks @Ani-Mayhem-Com 

I'll change the issue title, to be specifically about clarifying the prose in the spec, and I'll file a Firefox bug.

**Comment by AmeliaBR** [comment]
[Firefox bug, for reference](https://bugzilla.mozilla.org/show_bug.cgi?id=1343436)

**Comment by dirkschulze** [comment]
@AmeliaBR I do not really understand the issue. The spec text says:

> Then the implementation computes the lattice points for R, then continues getting additional pseudo random numbers relative to the last generated pseudo random number and computes the lattice points for G, and so on for B and A.

and

> The generated color and alpha values are in the color space determined by the color-interpolation-filters property

What about alpha channel needs to get clarified further?

**Comment by AmeliaBR** [comment]
Hmm... it looks like you already fixed it in https://github.com/w3c/fxtf-drafts/commit/537cfe4ac4ae798e5c38521c64d33e740c21c8dd

The issue was that the clamping range for the alpha channel (0 to 1) didn't match with the 0 to 255 range described in the prose.  You could further clarify that the clamping formula is for converting to a "color or alpha value", but the important thing is that the math makes sense.

**Comment by dirkschulze** [comment]
@AmeliaBR Good point! Done.
