### ISSUE TITLE
[filter-effects] Restore SVGFEConvolveMatrixElement#preserveAlpha IDL attribute

### ISSUE THREAD

**Issue by foolip** [w3c/fxtf-drafts#114]
Continuing/escalating https://www.w3.org/Bugs/Public/show_bug.cgi?id=28703

This IDL attribute was in in SVG 1.1:
https://www.w3.org/TR/SVG11/filters.html#InterfaceSVGFEConvolveMatrixElement

But is gone in Filter Effects:
https://drafts.fxtf.org/filters/#InterfaceSVGFEConvolveMatrixElement

Since the content attribute remains and the IDL attribute is still supported in 4 engines (Chromium, EdgeHTML, Gecko, WebKit) it seems simplest to just restore this attribute.

**Comment by AmeliaBR** [comment]
Were you able to find any past discussion suggesting this was an intentional choice to drop the IDL property, or was it likely just an oversight when re-formatting the specs?

**Comment by fsoder** [comment]
The origin of the removal is likely https://www.w3.org/2013/11/14-svg-minutes.html#item09

**Comment by AmeliaBR** [comment]
Ah, that makes more sense. (Removing the one remaining use of SVGAnimatedBoolean, after deprecating other uses, so the object interface could also be removed.)

But [along with similar SVG DOM removals based on browser requests](https://github.com/w3c/svgwg/issues/309), the question is whether the browsers are actually interested in removing it?

**Comment by longsonr** [comment]
I only speak for myself but I don't think we really are interested in removing it. It's there, it works fine, if it ain't broke...

**Comment by foolip** [comment]
Would removing SVGAnimatedBoolean be a step to some other worthwhile goal, or it a given that we're stuck with move SVGAnimated* interfaces forever? If so, removing just one doesn't seem worthwhile.

**Comment by foolip** [comment]
My suggestion is that if no implementer speaks up favor of removing (unshipping) this, then by default in 14 days or something it is resolved to add it back. Do you already have a process like that, and can it be raised on some regular call, F2F or well-subscribed email list?

**Comment by AmeliaBR** [comment]
Pinging @grorg and @dirkschulze, the active editors on the spec.  If they think it needs a resolution, or at least more implementer input, it could be discussed in CSS WG.

We've already got Blink & Firefox implementers on this thread voting for "If it ain't broke, don't fix it".  And for what it's worth, that's my preference, too.  (At least until we get a proper replacement for the SVG DOM data types!)

**Comment by foolip** [comment]
Ping again :)

**Comment by dirkschulze** [comment]
@foolip I think it needs a WG resolution that overrules the initial resolution. I do not have hard feelings either way.

**Comment by foolip** [comment]
Thanks @dirkschulze!
