### ISSUE TITLE
[css-masking] spec is unclear about how to handle no-clip parsing in shorthand

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#118]
The [definition of the `mask` shorthand](https://drafts.fxtf.org/css-masking-1/#the-mask) says:
> If one &lt;geometry-box> value is present then it sets both mask-origin and mask-clip to that value. If two &lt;geometry-box> values are present, then the first sets mask-origin and the second mask-clip.

This sentence doesn't account for the fact that there might be a `no-clip` value.  In particular:
* `border-box no-clip` has one &lt;geometry-box> but it presumably doesn't set `mask-clip` to `border-box`, contradicting the first sentence
* `no-clip border-box` has the same problem, but it also can't just set the first value as `mask-origin` and the second as `mask-clip`.

/cc @bzbarsky

**Comment by svgeesus** [comment]
Right, this should say that if the value is one geometry box _and nothing else_ then it sets both mask-origin and mask-clip. If the value has two items (two geometry boxes is one such case) then mask-origin and mask-clip are set separately.

**Comment by bzbarsky** [comment]
> Right, this should say that if the value is one geometry box and nothing else

That doesn't sound right.  What if it has two items: a geometry box and a mask reference?

**Comment by dirkschulze** [comment]
It seems like Firefox does the "right thing":

```html
<html>
<div style="mask: url(red.png) content-box"></div>
<div style="mask: url(red.png) content-box padding-box"></div>
<div style="mask: url(red.png) content-box no-clip"></div>
<div style="mask: url(red.png) no-clip content-box"></div>
```

1. `mask-origin` and `mask-clip` are both `content-box`
2. `mask-origin` is `content-box` and `mask-clip` is `padding-box`
3. `mask-origin` is `content-box` and `mask-clip` is `no-clip`
4. `mask-origin` is `content-box` and `mask-clip` is `no-clip`

So it is just a matter to put the spec intention and the behavior of Firefox (which both match) into words.
