### ISSUE TITLE
[filter-effects] Clarify the colour spaces used

### ISSUE THREAD

**Issue by debarshiray** [w3c/fxtf-drafts#127]
The text of the Filter Effects (https://drafts.fxtf.org/filters/) specification is either buggy or needs clarification when it comes to the colour spaces used for different operations.

For example, https://drafts.fxtf.org/filters/#ColorInterpolationFiltersProperty says that color-interpolation-filters applies to "all filter primitives". Then it goes on to say that "it has no effect on filter primitives like feOffset, feImage, feTile, feFlood or feTurbulence". However https://drafts.fxtf.org/filters/#elementdef-feturbulence says "generated color and alpha values are in the color space determined by the color-interpolation-filters property".

It also says "filter functions must operate in the sRGB color space".

For a simple effect like sepia (https://drafts.fxtf.org/filters/#sepiaEquivalent), I am left wondering whether the specified feColorMatrix should be applied on linear RGB values or perceptual ones.

**Comment by dirkschulze** [comment]
@debarshiray Note that there is a difference between filter functions and filter primitives. The former are functions used like `filter: blur(2px)` and always operate in `sRGB` regardless of the settings in `color-interpolation-filters` CSS property. The latter are used within a `&lt;filter>` element and do respect the `color-interpolation-filters` CSS property.

The note about `feTurbulence` in the `color-interpolation-filters` seems indeed to be a mistake and I removed that primitive. I also clarified the normative text for filter functions and how they relate to the specified values of `color-interpolation-filters`.

Closing the issue as fixed. If you think the changes are not satisfying feel free to reopen the issue.

**Comment by debarshiray** [comment]
Thanks for clearing that up!
