### ISSUE TITLE
[geometry] "The type of box is specified..."

### ISSUE THREAD

**Issue by cvrebert** [w3c/fxtf-drafts#128]
https://drafts.fxtf.org/geometry-1/#DOMRect

> Objects implementing the DOMRectReadOnly interface represent a rectangle.
> The type of box is specified by the method or attribute that returns a DOMRect or DOMRectReadOnly object.

https://drafts.csswg.org/css2/visuren.html uses "types of boxes" & "box's type" in reference to https://drafts.csswg.org/css2/visuren.html#box-gen , but I'm guessing this sentence intends to refer to https://drafts.csswg.org/css2/box.html#box-dimensions (content box vs. padding box vs. border box vs. margin box) instead? The wording could be clearer.

Also, the reference to a box comes as somewhat of a non-sequitur. Seems like the linkage between the box and the rectangle is missing.
E.g. "The type of box *which the rectangle represents* is..."

**Comment by dirkschulze** [comment]
This is a very strange sentence. DOMRect and rectangle have nothing to do with a box type. IMO this sentence should be removed.
