### ISSUE TITLE
[css-masking] definition of mask-type ignores mask-mode

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#129]
The [definition of `mask-mode: match-source`](https://drafts.fxtf.org/css-masking-1/#the-mask-mode) says:
> If the &lt;mask-reference> of the mask-image property is of type &lt;mask-source> the luminance values of the mask layer image should be used as the mask values.

This, however, ignores the [`mask-type` property](https://drafts.fxtf.org/css-masking-1/#the-mask-type), which changes what a &lt;mask> element's default behavior is.

I believe it should instead say that in this case (`mask-mode: match-source` on a `mask-image` of type &lt;mask-source>) the &lt;mask> element's `mask-type` property should be used.

**Comment by dirkschulze** [comment]
This is indeed an oversight!
