### ISSUE TITLE
[css-masking-1] was the position of 'mask-mode' in the 'mask' shorthand intentional?

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#13]
I previously reported this [on public-fx](https://lists.w3.org/Archives/Public/public-fx/2016JanMar/0058.html), but filing in github now.

css-masking-1 [defines](https://drafts.fxtf.org/css-masking-1/#the-mask) the mask shorthand so that the mask-mode value, if present, has to come immediately after the mask-image value.  This seems to be a bit constraining, and it's not clear if it was even intentional, since it seems almost like it could have been an editing error.  Maybe it was intentional, though.

If it was intentional, perhaps it should be explained in the prose, given that it's non-obvious and might be missed?

**Comment by heycam** [comment]
It's not apparent to me that there's any advantage to this.  I think we should just put a `||` between the mask-image and mask-mode values.  This is what Firefox implements.  AFAIK no other implementation supports mask-mode values in the shorthand yet.

*(/me wonders if that Agenda+ label has any effect in the fxtf repo...)*

**Comment by dbaron** [comment]
The WG resolved in today's teleconference to add the ||.

**Comment by dbaron** [comment]
Quoting from [today's teleconference minutes](https://lists.w3.org/Archives/Public/www-style/2016Nov/0107.html):
<blockquote>
<h3>Was the position of 'mask-mode' in the 'mask' shorthand intentional?</h3>

**dbaron**: Basically the mask shorthand is defined so that mask-mode has to be positioned right after mask-reference
**dbaron**: I feel like that was a typo rather than intentional where we want the shorthand to mostly allow arbitrary re-ordering except this thing. I believe Gecko impl as though there's a || but no one can answer if this is intentional.
**Rossen**: What is your proposed change?
dbaron: Add an or so that mask-mode can be anywhere in the mask-shorthand other than between position and size.
**Rossen**: Do we have a Blink implementation on that one?
**dbaron**: I don't know.
**dbaron**: I think there's implementation of the mask shorthand, but I don't know if there's mask-mode in it since it's newer.
**Rossen**: What about webkit?
**Rossen**: I don't hear anyone. Any other opinions on this?
**Rossen**: Objections?

**RESOLVED: mask-mode can be anywhere in the mask-shorthand other than between position and size**</blockquote>

**Comment by dbaron** [comment]
Fixed by #92.
