### ISSUE TITLE
[geometry] Avoid overloading constructor for DOMMatrix

### ISSUE THREAD

**Issue by zcorpan** [w3c/fxtf-drafts#135]
https://drafts.fxtf.org/geometry/#dommatrix

From https://github.com/heycam/webidl/issues/351

I believe we should change the `DOMString` overload to use `optional` with default value "", and remove the no-arg overload.

**Comment by annevk** [comment]
I think it would be better to avoid using the overload altogether. That just leads to poor API design.

**Comment by zcorpan** [comment]
Do you mean use IDL union, or move the sequence constructor to a static `fromArray()`?

**Comment by annevk** [comment]
Using a union.

**Comment by zcorpan** [comment]
OK I made a PR at https://github.com/w3c/fxtf-drafts/issues/136

I didn't use "" as the default value since as @bzbarsky pointed out the string version might go away in workers.
