### ISSUE TITLE
[filter-effects] List feMergeNode in the TOC

### ISSUE THREAD

**Issue by SebastianZ** [w3c/fxtf-drafts#139]
The [`<feMergeNode>`](https://drafts.fxtf.org/filters/#elementdef-femergenode) filter primitive is not listed in the table of contents, because it doesn't have a headline.

To make it easier to spot it, it should either get its own headline or be added to the "8.15. Filter primitive &lt;feMerge&gt;" headline.

Sebastian

**Comment by dirkschulze** [comment]
I agree that some elements like feMergeNode or the fefunc elements are harder to spot. Should get their dedicated headers.

**Comment by SebastianZ** [comment]
Great job, Dirk, for tightening up the spec. syntax! The elements are now listed in the TOC as expected.

Just one thing: The TOC is missing the arrow brackets of the elements now. I'm not sure whether that was also the case before your changes, though at least [in the TR they are there](https://www.w3.org/TR/filter-effects/#contents).

Is that something you can fix or does that require Bikeshed changes?

Sebastian

**Comment by dirkschulze** [comment]
@SebastianZ I think it was a compromise based on the Bikeshed conversion. I need to check if it can be solved somehow.
