### ISSUE TITLE
[geometry] DOMMatrix stringifier in workers

### ISSUE THREAD

**Issue by zcorpan** [w3c/fxtf-drafts#145]
https://drafts.fxtf.org/geometry/#dom-dommatrixreadonly-stringifier

> stringifier\(\)
> If is2D is true
> Return a DOMString in the form of a CSS Transforms &lt;matrix\(\)&gt; function where a is a attribute, b is b attribute, c is c attribute, d is d attribute, e is e attribute, f is f attribute\. \[CSS3\-TRANSFORMS\]
> Otherwise
> Return a DOMString in the form of a CSS Transforms &lt;matrix3d\(\)&gt; function where m11 to m44 are set to m11 to m44 attributes\. \[CSS3\-TRANSFORMS\]

In https://github.com/w3c/fxtf-drafts/issues/122 we limited CSS parser entry points for `DOMMatrix` to `Window`. Should we also limit the stringifier to `Window` (so that in workers it would stringify to "`[object DOMMatrix]`")?

cc @esprehn @chrishtr @foolip

**Comment by foolip** [comment]
At a glance I can't tell if `[Exposed=Window] stringifier` is allowed in Web IDL, but my initial reaction is that there wouldn't be much point in limiting this. The serialization code path seems to be standalone, and so making it work would be less work that limiting it, I think.

**Comment by chrishtr** [comment]
I think we should limit the special stringifier to the main thread, and return [object DOMMatrix]
in workers. Reasons: symmetry, simplicity for implementors.

**Comment by foolip** [comment]
I wouldn't really mind that, but isn't it actually more complicated for implementors?

**Comment by zcorpan** [comment]
Another aspect is that https://github.com/w3c/fxtf-drafts/issues/120 proposes making the serializer throw if there are NaN/Infinity values, which could be nice to avoid in workers.

**Comment by zcorpan** [comment]
As far as I can tell from WebIDL, `[Exposed=Window] stringifier;` should work. `stringifier;` is shorthand for `stringifier DOMString ();`, which is an interface member, and `[Exposed]` applies to interface members.
