### ISSUE TITLE
[geometry] 0/-0 equality in "validate and fixup", isIdentity, is2D

### ISSUE THREAD

**Issue by zcorpan** [w3c/fxtf-drafts#152]
https://drafts.fxtf.org/geometry/#dommatrix-attributes

> The isIdentity attribute must return true if m12 element, m13 element, m14 element, m21 element, m23 element, m24 element, m31 element, m32 element, m34 element, m41 element, m42 element, m43 element are 0  and m11 element, m22 element, m33 element, m44 element are 1\. Otherwise it must return false\.

Should this treat 0 and -0 as equal or different? Also for the logic for `is2D`...

https://drafts.fxtf.org/geometry/#webidl-unrestricted-double-same treats them as different, but that's more of a side-effect of the definition; the purpose was to treat NaN as equal to NaN. This could be changed to check for NaN specifically, and then doing an equality check where 0 and -0 are equal.

Opinions?

**Comment by domenic** [comment]
In general we've tended toward treating +0 and -0 as equivalent in new JS APIs that depend on identity, using the SameValueZero operation. This includes Map, Set, and Array.prototype.includes. I don't think this has come up very often in the web platform yet though.

**Comment by domenic** [comment]
My only other thought is that maybe we could do this on a broader web platform level, by censoring all -0s when converting from JS values to (unrestricted) double|floats. I think that would probably not be good for perf reasons, but I am just guessing, without knowledge of how the bindings handle the translation today.

**Comment by zcorpan** [comment]
I think it makes more sense to preserve -0 as -0, so it's more consistent with JS.

Treating +0 and -0 as equivalent sounds good. I'll try to fix this for Geometry.

**Comment by zcorpan** [comment]
As SameValueZero is exactly what I want. Great!
