### ISSUE TITLE
[geometry] Figure out if ClientRect/SVGPoint/SVGRect/SVGMatrix should be aliases

### ISSUE THREAD

**Issue by zcorpan** [w3c/fxtf-drafts#163]
https://drafts.fxtf.org/geometry/#dom-domrect-domrect-x-y-width-height-height

> interface DOMRect

https://github.com/search?l=JavaScript&q="instanceof+clientrect"+OR+"clientrect.prototype"&type=Code&utf8=✓ shows it's rare but non-zero to assume that `window.ClientRect` exists, so we should probably add an alias for it like for WebKitCSSMatrix et al.

**Comment by zcorpan** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=719246

**Comment by zcorpan** [comment]
If we decide to not alias `ClientRect`, then we should check if we can get away with fewer aliases overall (`SVGMatrix` etc). cc @foolip

**Comment by zcorpan** [comment]
@foolip mentioned in the Chromium bug that Gecko has only `DOMRect`, not `ClientRect`.

httparchive search for `.{50}\bClientRect\b.{50}` and grouping the matches:

num | match
----|------
108 | `.i.x$(a)\|\|vdb.i.E$(a)},IT:function(a){return c(a,"ClientRect")\|\|c(a,"DOMRect")},hj:function(a){return void 0!=`
4 | `.waa(a)\|\|vdb.i.Caa(a)},EU:function(a){return c(a,"ClientRect")\|\|c(a,"DOMRect")},yj:function(a){return void 0!=`
2 | `.info("bcTruncate: browser doesn't have Range and ClientRect support; aborting");return}var elems=this.filter(`
2 | `.aea(a)\|\|vdb.i.gea(a)},iX:function(a){return c(a,"ClientRect")\|\|c(a,"DOMRect")},Pj:function(a){return void 0!=`
1 | `:this},bcr:{value:l\|\|g.exports.ClientRect.getBoundClientRect(document.body)},origin:{value:o\|\|new g.exports.Po`
1 | `("./SSiteNav").SSiteNav,ClientRect=requirejs("lib/ClientRect"),env=require("./environment"),cssCompat=require(`
1 | `","lib/Model","lib/ZenView","lib/StyleSheet","lib/ClientRect","lib/Cookie","modules/rlx-transition","modules/r`
1 | `.join(", ")+"]";break;case"ApplicationCache":case"ClientRect":case"DOMApplicationCache":case"DOMStringList":ca`
1 | `&&d!=null){b.value=a.Width;d.value=a.Height}}this.ClientRect=new Rect(0,0,a.Width,a.Height);this.Rect=CopyRect`
1 | `\n    new(): CharacterData;\r\n}\r\n\r\ninterface ClientRect {\r\n    bottom: number;\r\n    readonly height: `
1 | ` strict";var klass=require("mbx/src/class").class,ClientRect=require("mbx/src/dom/ClientRect").ClientRect,Even`


The `.info("bcTruncate: browser doesn't have Range and ClientRect support; aborting");return}var elems=this.filter(` match looks a bit worrying, but it's actually checking this:

```
hasCSSOM:{className:"cssom",test:function(){return document.createRange&&
document.createRange().getClientRects}}
```
http://s4.bcbits.com/tmpdata/cache/global_head_bundle_min_313e367f1f56dfa01981fc3f0ed4396b.js
from site http://lapfoxtrax.com/

Nothing there looks like it's trying to identify Gecko.

Most of the other matches seem to already account for `DOMRect`, so I think we should try not having a `ClientRect` alias.

**Comment by zcorpan** [comment]
cc @cdumez @dbaron @travisleithead

**Comment by zcorpan** [comment]
Searching on GitHub reveals a few hundred matches for each of "new SVGPoint", "new SVGRect" and "new SVGMatrix". Not all of them are relevant since some are custom functions etc, but still. Since these have constructors (unlike `ClientRect`), and have been around for a long time, it seems best to have aliases for them.

**Comment by fsoder** [comment]
SVGPoint, SVGRect and SVGMatrix have been constructable that way (although speced as such for a short while in an SVG2 draft), so I wonder what those instances actually do. (These types would only be constructable through SVGSVGElement.createSVG{Point,Rect,Matrix}.)

**Comment by AmeliaBR** [comment]
The `new` structures are unexpected, since as Frederick says that would just throw an error in most browsers.  But it is possible that someone could be using an `instanceof` test, or a `if (Window.SVGPoint)` test, so there is probably some value in legacy aliases.

**Comment by zcorpan** [comment]
I didn't realize browsers didn't implement the constructors for `SVG*`. Anyway, less risk to keep them around.
