### ISSUE TITLE
[filter-effects] Clarify mapping of Cs and Cb to in and in2 in feBlend

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/fxtf-drafts#165]
https://www.w3.org/TR/filter-effects/#element-attrdef-feblend-mode

The definition for the mode attribute of `<feBlend>` states:

> One of the blend modes defined by “Compositing and Blending Level 1” [COMPOSITING-1]

However that specification defines the blend functions in terms of source (Cs) and backdrop (Cb) parameters.  We should specify how `in` and `in2` map to those two values.

From testing (Chrome and FF) it appears that Cs maps to `in`, and Cb maps to `in2`.

**Comment by AmeliaBR** [comment]
That's a very good point. I can never remember whether `in` or `in2` should be "on top".  (I always think the second input should go on top of the first).  

PS, I checked and [SVG 1.1 wasn't much clearer](https://www.w3.org/TR/SVG11/filters.html#BlendingTable): the formulas use image A (top for normal blending) and image B (background), without explicitly saying which one is `in` versus `in2`.  But that is presumably where the "second image is the background" interpretation comes from.

**Comment by dirkschulze** [comment]
I added a sentence for feBlend and feComposite that shall make it more obvious which input maps to source or destination/backdrop.
