### ISSUE TITLE
[filter-effects] "standard deviation" versus "blur radius" in blur() and dropshadow()

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/fxtf-drafts#172]
The SVG `<feGaussianBlur>` filter primitive uses standard deviations to define the amount of blur.  In contrast, `box-shadow` and `text-shadow` use a "blur radius".  The Backgrounds and Borders spec has since been updated to clarify that the [blur radius is twice the standard deviation](https://drafts.csswg.org/css-backgrounds/#shadow-blur).

The Filters spec, however, throws around the two terms as if they are directly interchangeable.

The parameter passed to the [`blur()` shorthand filter function](https://drafts.fxtf.org/filters/#funcdef-filter-blur) is described as both "standard deviation" and as "radius"  (also [in the longhand definition](https://drafts.fxtf.org/filters/#blurEquivalent)).

Even worse (because it affects normative requirements), the [`drop-shadow()` shorthand filter definition states that](https://drafts.fxtf.org/filters/#funcdef-filter-drop-shadow) "Values are interpreted as for box-shadow", but then [gives a longhand equivalent](https://drafts.fxtf.org/filters/#dropshadowEquivalent) that uses the radius as `stdDeviation` in `<feGaussianBlur>`.

The longhand for `drop-shadow()` should probably be re-defined in terms of [`<feDropShadow>`](https://drafts.fxtf.org/filters/#feDropShadowElement), but that doesn't avoid the issue: `<feDropShadow>` still uses `stdDeviation`, while the shorthand uses the radius.

A consistent terminology is required throughout.  I would recommend using words like "the standard deviation or half-radius of the blur" to emphasize the relationship.

It might also be helpful to add a longer informative note explaining the difference between the standard deviation `blur()` parameter and the shadow blur radius.

**Comment by fsoder** [comment]
Slightly related to #102

**Comment by dirkschulze** [comment]
See https://github.com/w3c/fxtf-drafts/issues/102#issuecomment-307142696

**Comment by AmeliaBR** [comment]
Closing as a duplicate.  Still needs edits, but that tag is already on #102.
