### ISSUE TITLE
[filter-effects][compositing] What is "no-composite" blending?

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/fxtf-drafts#173]
The [attribute-definition section of `<feBlend>`](https://drafts.fxtf.org/filters/#elementdef-feblend) includes a (new relative to SVG 1.1) `no-composite` boolean attribute with the following description:

> If the no-composite attribute is present, the specified blend mode must not use alpha compositing. The necessary modifications are defined by “Compositing and Blending Level 1”.

There is no description I can find in [C&B Level 1](https://drafts.fxtf.org/compositing-1/#blending) or [Level 2](https://drafts.fxtf.org/compositing-2/) about blending without alpha compositing.  What is this supposed to refer to?

The `no-composite` attribute is not listed in the blue-box element definition.  Was it supposed to have been removed?

**Comment by dirkschulze** [comment]
Blend mode algorithms usually are described with compositing steps. They can be described w/o compositing also. That is what filter effects asks for.

C&B says:
> Conceptually, the colors in the source element are blended in place with the backdrop. After blending, the modified source element is composited with the backdrop. In practice, this is usually all performed in one step.

@cabanier The C&B spec currently has the steps for mixing compositing and blending. Does it have the pure blending formula as well?

**Comment by mstange** [comment]
All the `B(Cb, Cs)` formulas in [C&B Level 2](https://drafts.fxtf.org/compositing-2/#blending) describe the pure blend step. The compositing that happens afterwards to compute the final composited color, `Cr`, uses B(Cb, Cs) as one of its inputs and is mentioned in the introductory section of the Blending chapter:

```
Cr = (1 - αb) x Cs + αb x B(Cb, Cs)
```

**Comment by cabanier** [comment]
The issue with feblend is that it combines blending and compositing. This mean that the filter operation composites with the backdrop and this result is then again composited.
This results in double compositing which gives the wrong result when there's alpha.

no-composite was supposed to skip the compositing operation during the filter to work around this problem.
https://www.w3.org/TR/compositing-1/#blending gives the result with regular alpha compositing. For no-composite=true, the composting part becomes "copy" (https://www.w3.org/TR/compositing-1/#porterduffcompositingoperators_src) and the blending part stays the same

**Comment by dirkschulze** [comment]
@cabanier But as you said, https://www.w3.org/TR/compositing-1/#blending already had alpha compositing. So don't we need blending w/o alpha compositing that gets combined with "copy"?

**Comment by cabanier** [comment]
I'm not sure I follow. Blending itself doesn't composite. (The original spec broke this out but that was removed to get to CR which makes it a bit confusing.)
For the usual case, blending calculates a new source color with the following formula: 
   Cr = (1 - αb) x Cs + αb x B(Cb, Cs)
with B the blending formula.
This new source color is then composited as usual using source-over.

For a no-composite filter, you just execute the blending step.

**Comment by cabanier** [comment]
> @cabanier The C&B spec currently has the steps for mixing compositing and blending. Does it have the pure blending formula as well?

Yes: Cr = (1 - αb) x Cs + αb x B(Cb, Cs)

**Comment by dirkschulze** [comment]
Added direct link to "mixing" formula without compositing step following the explanation from @cabanier.

@AmeliaBR Please comment feel free to re-open the issue if you think the spec text is not satisfying.
