### ISSUE TITLE
[filter-effects] Why can't opacity() filter function ever increase opacity?

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/fxtf-drafts#178]
The description of [the shorthand `opacity()` filter function](https://drafts.fxtf.org/filters/#funcdef-filter-opacity) says:

>  Values of amount over 100% are allowed but UAs must clamp the values to 1.

Was there a practical reason why the function cannot be used to increase opacity?  Have browsers implemented the clamping of the input parameter?  Or do they only clamp the final value?  (Sorry, don't have time to test right now...)

I think it removes much of the usefulness of the function that it can't be used to increase opacity of semi-transparent regions (e.g., of blurred edges created by `blur()` or `drop-shadow()` ).

**Comment by tabatkins** [comment]
I think it's kinda weird to do it multiplicatively; in particular, it means that something which is currently 0% opacity can't ever become visible, but something that's 1% can be (with an opacity of 10000%, for example).  But opacity() can't do additive modification.

**Comment by tabatkins** [comment]
Or, from another direction: all the filters can be conceptually thought of as just rendering the subject to a bitmap and then fiddling with the pixels.  To have >100% opacity work, you'd need to allow the alpha channel of the pixels to be an unbounded value, which is very inconsistent with current models of pixel color.

**Comment by AmeliaBR** [comment]
>  I think it's kinda weird to do it multiplicatively; in particular, it means that something which is currently 0% opacity can't ever become visible, but something that's 1% can be

That's exactly the functionality I want!
You can currently apply multiplicative alpha with `<feComponentTransfer>` and I use it to make blurred edges more opaque (without also suddenly creating a solid background out of nothing).  

And as far as weirdness goes, I'd say it's even less intuitive for `brightness`, which also works as a multiplicative factor: you can use `brightness(255)` to turn every shade of gray that isn't pure black into white, but black itself will never get any brighter.  (Also true for pure saturated colors with one channel at 0; that channel never gets any brighter.)

> To have >100% opacity work, you'd need to allow the alpha channel of the pixels to be an unbounded value, which is very inconsistent with current models of pixel color.

I'm not saying that the end result should be something greater than 100% opacity.  The output of the filter operator would be clipped to the allowable range, just like it is for every other operator.

_________________________

It would be nice to also have an additive option for both `opacity` and `brightness`.  Maybe a second parameter to the function (which would then be the `intercept` in the `<feComponentTransfer>` function).  But that's a separate feature, I think.

**Comment by AmeliaBR** [comment]
> I use it to make blurred edges more opaque (without also suddenly creating a solid background out of nothing).

PS. This is used in the nice SVG version of the  so-called "gooey" filter effect.  In contrast, the current all-shorthand version that is popular requires adding a solid background and using `contrast()`, which ruins colors.

**Comment by dirkschulze** [comment]
@AmeliaBR Just to verify, you want the intermediate opacity value to increase beyond 100% but the input as well as the output of the `opacity()` effect would still be clamped?

**Comment by AmeliaBR** [comment]
Inputs and outputs would be clamped.  The multiplicative factor would not be clamped.  So `opacity(200%)` would double the per-pixel alpha values of the input image, and then clamp them (per pixel) to the range 0-1.

The equivalent long-hand definition would be:

```xml
<filter id="opacity">
  <feComponentTransfer>
      <feFuncA type="linear" slope="[amount]"/>
  </feComponentTransfer>
</filter> 
```

where `[amount]` is the shorthand parameter as a decimal number.

**Comment by AmeliaBR** [comment]
A test of how browsers currently handle opacity filter values greater than 1 / 100%:
https://codepen.io/AmeliaBR/pen/ypRgEY?editors=0100

Sadly for me, they all seem to match the spec. Parameters are clamped to 1, so that opacity of a partially-transparent element can never be increased with the shorthand filters.

**Comment by svgeesus** [comment]
> Sadly for me, they all seem to match the spec. Parameters are clamped to 1, so that opacity of a partially-transparent element can never be increased with the shorthand filters.

That seems to imply that we should continue to require clamping, but then later have an explicit no-clamping opt-in.

**Comment by smfr** [comment]
I think we should keep opacity() as a multiplicative alpha effect, just like the opacity CSS property. If we want to allow some different behavior, I think that would be a new filter that exposes the kinds of things that feComponentTransfer can do.

**Comment by AmeliaBR** [comment]
> as a multiplicative alpha effect

Technically, what I'm asking for would still be a multiplicative alpha effect. Just allowing multiplication with values greater than 1. 😉

`opacity()` as currently defined has very few use cases in the `filter` property, since there's nothing it can do that the `opacity` property can't.  I've seen it [used as part of workarounds for broken supports testing](https://codepen.io/tigt/post/blurred-background-image-with-fallback), that's all. It would have some use in the image filter function (if anyone implemented that).

I agree that adding any other behavior (e.g., additive offsets) would be something to defer to another level of the spec.

The problem with defering `opacity(150%)` to a future spec is that, as it is currently spec'd, that is a valid declaration. The parser accepts it. It just doesn't have any effect different from `opacity(100%)`. So changing later becomes a compat risk.

(Maybe it's already a compat risk, I don't know. People could be doing weird things with `calc` and variables, confident that if the result is at least 100% then the filter won't change anything.)

Adding this functionality in the future would require adding a separate function (`alpha()`, maybe), that has the full functionality that `opacity()` should have had.

**Comment by AmeliaBR** [comment]
As promised, I created [a new issue](https://github.com/w3c/fxtf-drafts/issues/256) to track a more general filter function for arbitrary color-channel modification in Filter Effects Level 2. I even came up with a full-fledged syntax proposal, by borrowing from the Colors 4 color modification functions.
