### ISSUE TITLE
[motion] default reference box for basic shape

### ISSUE THREAD

**Issue by ewilligers** [w3c/fxtf-drafts#189]
[offset-path](https://drafts.fxtf.org/motion-1/#offset-path-property)
should specify the default reference box for a basic shape.

For comparison:

[shape-outside](https://drafts.csswg.org/css-shapes/#shape-outside-property)
If <shape-box> is not supplied, then the reference box defaults to margin-box.

[clip-path](https://drafts.fxtf.org/css-masking-1/#the-clip-path)
If no reference box is specified, the border-box will be used as reference box.

**Comment by jihyerish** [comment]
I think that defining the `border-box` as the default reference box for `<basic-shape>` value seems reasonable for `offset-path`.

If there is the border of the containing block where the offset path will be drawn, it’ll be expected to position the box along it. Also, the `border-box` reference box helps keep the offset path synchronized with the border if margins are used.
The `margin-box` reference box would be useful when it's important to wrap the containing block around with the offset path and influence the area beyond the dimensions of the containing block. But `offset-path` doesn’t need to change the relationship of other boxes around the containing block.
