### ISSUE TITLE
Typos in Motion Path

### ISSUE THREAD

**Issue by ewilligers** [w3c/fxtf-drafts#19]
Hi jihyerish, I noticed a few typos while reading your Motion Path patch
https://github.com/w3c/fxtf-drafts/pull/14

motion-1/Overview.bs

line 136
	the element can be positioned in the used of polar coordinates.
should be
	the element can be positioned with the use of polar coordinates.

line 145
	position for consistency with other CSS specifications such as [[!CSS3VAL]], <<angle>> value.
should be
	for consistency with other CSS specifications such as [[!CSS3VAL]], <<angle>> value.
(as the preceding line doesn't have "x axis position")

line 177
	<img alt="An image of elements positioned without contain" src="images/offset_distance_with_contain.png" style="width: 200px;"/>
should be
	<img alt="An image of elements positioned with contain" src="images/offset_distance_with_contain.png" style="width: 200px;"/>

line 227
	unless the element is an SVG element with out an associated CSS layout box.
should be
	unless the element is an SVG element without an associated CSS layout box.

line 294
	the containing block, the closest side takes the edge where the initial position
should be
	the containing block, the closest side takes the edge that the initial position

line 606
	<h3 id="motion-shorthand">Offset shorthand: The 'offset' property</h3>
should be
	<h3 id="offset-shorthand">Offset shorthand: The 'offset' property</h3>

**Comment by jihyerish** [comment]
Hi ewilligers, thanks for your comments.
I will fix those typo errors.

> line 606
Offset shorthand: The 'offset' property
should be
Offset shorthand: The 'offset' property

But I wonder, how line 606 should be changed.

**Comment by jihyerish** [comment]
@ewilligers I fixed typo errors.

But I couldn't resolve about line 606 mentioned in your comment above.
Does it relate to Issue #24 ?

**Comment by ewilligers** [comment]
> But I couldn't resolve about line 606 mentioned in your comment above.

Sorry, Markdown processed my change. I am suggesting that the id change from motion-shorthand to offset-shorthand.

**Comment by jihyerish** [comment]
Got it : ) I also fix that.
