### ISSUE TITLE
[filter-effects-1] What happens on feImage without valid resource?

### ISSUE THREAD

**Issue by dirkschulze** [w3c/fxtf-drafts#193]
Imported from https://www.w3.org/Bugs/Public/show_bug.cgi?id=27221

> What happens if xlink:href of feImage references an invalid or not existing resource?
> 
> The attached example has an feImage element that references a non-existent image. It is for testing purpose in different browsers.
> 
> The test starts with inverting the SourceGraphic color so that we know if a filter was applied to the element or not.
> 
> The it references the not existing image. The test also applies a subregion on the feImage element.
> 
> Then the opacity of the feImage result gets inverted.
> 
> Then we composite the previous result on top of the inverted SourceGraphic.

**Comment by dirkschulze** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27221#c1

> The result on various SVG viewers:
> 
> Chrome: You see a "missing image" icon covering the top left quarter of an aqua colored square.
> 
> Safari: You see a "missing image" icon covering the top left quarter of an aqua colored square.
> 
> Firefox: You just see an aqua colored square.
> 
> Opera (Presto): You see a black square covering the top left quarter of an aqua colored square.
> 
> IE 11: You see a black square covering the top left quarter of an aqua colored square.
> 
> InkScape: Crashes on windows.
> 
> Batik: You see a "missing image" icon covering the top left quarter of an aqua colored square.
> 
> Illustrator: You just see an aqua colored square.
> 
> 
> 
> All viewers do apply the filter regardless of the missing image resource. But the behavior is pretty different across browsers.
> 
> IE, Opera: Missing image is treated as transparent black.
> Firefox, Illustrator: Missing image acts as a null filter even for filter primitives applied on top of feImage.
> Safari, Chrome: General behavior as for IE, Opera but taking the "missing image" instead of transparent black.

**Comment by BigBadaboom** [comment]
Related discussion from the SVG mailing list:

https://lists.w3.org/Archives/Public/www-svg/2014Nov/0034.html

**Comment by AmeliaBR** [comment]
Specifically, the SVG WG resolution (from the link Paul posted):

> RESOLUTION: If feImage refers to a missing resource, it should
   produce transparent black such that it fills the filter
   primitive subregion

**Comment by fsoder** [comment]
FWIW, IIRC, Blink-based browsers should now produce transparent black in this case (i.e no longer has the behavior observed in Nov 2014.)

**Comment by dirkschulze** [comment]
Issue was fixed with https://github.com/w3c/fxtf-drafts/commit/92498140fd194d19b30d3946bcdf98b5cdbc0053 already.

Spec text says:
> A `href` reference that is an empty image (zero width or zero height), that fails to download, is non-existent, or that cannot be displayed (e.g. because it is not in a supported image format) fills the filter primitive subregion with transparent black.
