### ISSUE TITLE
[geometry] JSON serialization of a DOMRectList

### ISSUE THREAD

**Issue by zcorpan** [w3c/fxtf-drafts#199]
https://github.com/w3c/fxtf-drafts/pull/186 adds back `DOMRectList`.

See https://www.w3.org/Bugs/Public/show_bug.cgi?id=27428 - consider specifying `toJSON`/ `serializer` as an array.

cc @bzbarsky @cdumez @hwanseung

**Comment by tobie** [comment]
So you should just define your own `toJSON` operation that returns a`sequence<DOMRect>.

**Comment by dirkschulze** [comment]
Beside the stated use case in the referenced Bugzilla issue there is not much interest it seems. My suggestion would be to either close this issue or defer it to level 2 of Geometry Interfaces.

**Comment by annevk** [comment]
Closing this seems reasonable to me. In general we don't define toJSON unless there's a compelling use case.

**Comment by zcorpan** [comment]
OK with me to close this.
