### ISSUE TITLE
No fill-rule for Motion Path

### ISSUE THREAD

**Issue by ewilligers** [w3c/fxtf-drafts#20]
I understand there was a decision to remove fill-rule from the path function, which is used by motion-path (now offset-path).

motion-1/Overview.bs

line 207
	<dt><dfn>path()</dfn> = path([ <<fill-rule>> ,]? <<string>>)</dt>
should be
	<dt><dfn>path()</dfn> = path(<<string>>)</dt>

Lines 212..215 can be removed.

**Comment by jihyerish** [comment]
@ewilligers 
I didn't know about the decision and now I catch up with the history of the discussion.
Thanks for your comment!
