### ISSUE TITLE
[filter-effects] drop-shadow() null value for interpolation is incorrect

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/fxtf-drafts#204]
Regarding the `drop-shadow()` filter shorthand, the [spec](https://drafts.fxtf.org/filters/#funcdef-filter-drop-shadow) currently says:

> The initial value for interpolation is all length values set to 0 and the used color is taken from the color property.

However, a zero-offset, zero-blur shadow in `currentColor` is *not* the same as no shadow at all.
If there are semi-transparent regions in the element, you will see a colored shadow through them.  Chrome, Safari, and Firefox all interpolate the filter starting from a _transparent_ shadow when transitioning from `filter: none`.   

(MS Edge has so many bugs I at first thought it was ignoring the filter declaration altogether.  But the problem seems to be that `currentColor` is being treated as `transparent`.  Also, they don't interpolate the transition, so you need to hover for a few seconds to see the hover state.)

The spec should be changed to match the (majority of the) browsers.

Demo/test case: https://codepen.io/AmeliaBR/pen/xrPOxj

- 1st sample has a `currentColor` zero-offset, zero-blur shadow
- 2nd sample has no filter (note that it looks different!)
- 3rd sample starts with no filter, but on hover transitions to a colored, blurred, offset shadow

(Aside: Thanks Dirk for banishing the word "lacuna" from the spec!)

**Comment by dirkschulze** [comment]
@AmeliaBR If you remove the color value then you'll actually see that all browsers do use the currentColor as it is speced. In your last  example though, the initial animation value from filter `none` to a `drop-shadow` is different.

Note that the spec does make a difference between not applied filter and a used drop-shadow filter. However, for animations all browsers do make a difference and do not take the initial values. That means that the interpolation text needs to differ between initial values for not specified values and interpolation from `none` to a specified `drop-shadow`. Do you follow me?

**Comment by AmeliaBR** [comment]
@dirkschulze Yes, exactly.  A filter with an unspecified colour should use `currentColor`, so in that sense it's the initial/default value (and glad to find the browsers are using it consistently now; they didn't use to!).

But that's not the same as "the initial value for interpolation", which needs to be equivalent to `none`. 

Perhaps a better name would be the "null value for interpolation" or "no-effect value for interpolation", or just simply "the value equivalent to none".  Certainly, the automatic link on "initial value" isn't helping to clarify anything.

**Comment by dirkschulze** [comment]
After some testing with `mix-blend-mode` I am recently sure that the initial value for interpolation of color is `transparent` but for omitted color is `currentColor` in implementations. Will update the specification in a bit.

**Comment by dirkschulze** [comment]
@AmeliaBR Closing the issue. Feel free to reopen if the spec changes are not satisfying.
