### ISSUE TITLE
[filter-effects] Luminance coefficients are slightly changed from SVG 1.1

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/fxtf-drafts#206]
In response to my griping on Twitter that the `luminosity` used in blend modes isn't compatible with the `luminance` used in Masking and Filters, @nikosandronikos [discovered](https://twitter.com/nandronikos/status/879872647730876416) that the "luminance" coefficients in the [Filter Effects spec](https://drafts.fxtf.org/filters/#attr-valuedef-type-luminancetoalpha) don't match the ones from [SVG 1.1](https://www.w3.org/TR/SVG11/filters.html#feColorMatrixValuesAttribute).

- Filters Level 1: luminance = 0.2126R + 0.7152G + 0.0722B
- SVG 1.1: luminance = 0.2125R +  0.7154G + 0.0721B

The values used in the Filters spec are also incorporated by reference by [CSS Masking](https://drafts.fxtf.org/css-masking-1/#MaskValues).

The difference is slight (~0.01%), but if there was a very good reason for the change (e.g., compatibility with some 3rd standard), there should be a note explaining that.  Otherwise, I'm assuming it was an unintentional error.

**Comment by svgeesus** [comment]
These values come from the conversion from sRGB primaries to CIE XYZ (in this case, just Y which is luminance). To a higher precision, the correct values are:
0.2126729  0.7151522  0.0721750
rounded to 4 significant figures that would be
 0.212**7** 0.7151  0.07218
but my preference would simply be to use the higher precision values 9in both SVG and in filters). 
SVG 1.1 should be errata'd.

For a fuller description, see http://www.brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html

**Comment by AmeliaBR** [comment]
Is there an "official" source for the luminance coefficients that can be used as a reference?

@cabanier says that WebKit and Firefox (at least) use the new numbers, so if there is a valid reason for them that's fine. But then there should be a note in the spec saying they were changed to be closer to {official reference}. (I'm not sure if we're still compiling errata for SVG 1.1, but I guess that could be done, too.)

It's such a tiny difference, but it makes it look sloppy when one spec has different values from another.

**Comment by svgeesus** [comment]
The official specification is **IEC 61966-2-1:1999** 
Multimedia systems and equipment - Colour measurement and management - Part 2-1: Colour management - Default RGB colour space - sRGB 
https://webstore.iec.ch/publication/6169

I agree it looks sloppy and the values in Filters are closest to the correct ones.

**Comment by dirkschulze** [comment]
@AmeliaBR agree with you an informative note as a minimum should be added.
