### ISSUE TITLE
[geometry] Restore DOMMatrixReadOnly.scaleNonUniform() for backward compatibility with SVGMatrix

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/fxtf-drafts#214]
https://drafts.fxtf.org/geometry-1/#svgmatrix

`SVGMatrix` is aliased to `DOMMatrix`, but the version of `DOMMatrixReadOnly` in the current draft is not backward compatible. This is due to the removal of `scaleNonUniform()`.

**Comment by zcorpan** [comment]
This changed as part of:

> Changed DOMMatrixReadOnly and DOMMatrix to be compatible with WebKitCSSMatrix:
>
> * Changed the scale() and scaleSelf() methods to be more like the previous scaleNonUniform()/scaleNonUniformSelf() methods, and dropped the scaleNonUniform* methods.

See https://github.com/whatwg/compat/issues/19#issuecomment-173275699

We could add back `scaleNonUniform()` but it would be nice to have some data on how much it is used. @foolip @fsoder

**Comment by foolip** [comment]
This aliasing hasn't happened in Blink yet, and I'd support harmonizing by adding things to DOMMatrix(ReadOnly), unless the methods are somehow very silly. Should we just do this, or would use counters help?

**Comment by zcorpan** [comment]
It seems marginally nicer API to not have them, but if usage is non-zero then we should just add them to avoid breaking things when SVG APIs start returning `DOMMatrix`es.

There's a use counter for https://www.chromestatus.com/metrics/feature/timeline/popularity/1089 - is that just for `createSVGMatrix()` or for anything that returns an `SVGMatrix`? If the latter, it would be an upper bound for `scaleNonUniform`, if the former, it doesn't say much.

**Comment by fsoder** [comment]
It is only counting `SVGSVGElement.createSVGMatrix()`.

**Comment by dirkschulze** [comment]
I'd be in favour for not taking the risk and adding it back to the spec again. I know that quite a few tests in the WebKit repo use `scaleNonUniform()`. Of course they could get changed but it rather should be seen as a sign that content might exist. Especially since we do not have reliable use counter it seems.

**Comment by zcorpan** [comment]
@foolip can you check httparchive?

**Comment by foolip** [comment]
Not clear from GitHub notification email, but fixed by merging https://github.com/w3c/fxtf-drafts/pull/318.
