### ISSUE TITLE
[geometry] New DOMMatrix2DInit validating is confusing

### ISSUE THREAD

**Issue by fserb** [w3c/fxtf-drafts#217]
https://drafts.fxtf.org/geometry/#dommatrixinit-dictionary
https://github.com/w3c/fxtf-drafts/issues/210
https://github.com/w3c/fxtf-drafts/pull/211

Is there a reason for us not having a fromMatrix(DOMMatrix2dInit other) on the spec too? Given that we must validate matrix on setTransform (for canvas2D), we need to be able to create those matrices anyway. 

Also, at least on Chrome's implementation, the new validate and fixup as suggested on the pull request is messy.
We can't make a generic validate function for both of them, which means that both variants (DOMMatrix2DInit and DOMMatrixInit) have to be implemented independently. Which means that "ignore3D" doesn't solve any implementation problem, but adds more complexity to the spec and weird code duplication.

I'd suggest we move to a validate and fixup that does: validate and fixup for DOMMatrix2DInit. And validate and fixup for DOMMatrixInit that starts with something like "all the DOMMatrix2DInit validation plus...". I'll try a spec change tomorrow for that, but please let me know what you think.

**Comment by junov** [comment]
cc @zcorpan

**Comment by zcorpan** [comment]
I'm happy to restructure the requirements to better match how it's implemented. It looks like something like what you suggest is how it was implemented in https://bugs.webkit.org/show_bug.cgi?id=176048 also.

A thing to keep in mind is that, as I understand it, WebIDL dictionaries can't be type-checked, and we can't use an overload or union for `fromMatrix()`, but we could add a separate `fromMatrix2D()`. Please file a new issue for extending the exposed API.
