### ISSUE TITLE
[filter-effects] hue-rotate() is being used with unitless zero angle

### ISSUE THREAD

**Issue by ewilligers** [w3c/fxtf-drafts#228]
In April we [resolved](https://github.com/w3c/csswg-drafts/issues/1162#issuecomment-293637767) that '0' is no longer supported as a valid value for angles.

filter was already shipping with support for [hue-rotate](https://drafts.fxtf.org/filter-effects/#funcdef-filter-hue-rotate)(0) so Chrome added a use counter.

The [results](https://www.chromestatus.com/metrics/feature/timeline/popularity/2007) indicate that hue-rotate(0) is being used in 0.013% of page views.

To avoid breaking these pages, we could add an exception:
`hue-rotate( <angle> )`
->
`hue-rotate( [ <angle> | <zero> ] )`

This would be consistent with [gradients](https://drafts.csswg.org/css-images-3/#linear-gradients) and [transform](https://drafts.csswg.org/css-transforms/#valdef-transform-rotate), which are already
exceptions explicitly specified to support unitless 0, for the same reason.

**Comment by tabatkins** [comment]
+1 to adding it as an exception. We won't be doing this anymore, but it's already out there with non-negligible usage.

**Comment by dbaron** [comment]
I'm fine with such a resolution.  However, if we're making changes to already-implemented features, I'd like a web-platform-test to be added concurrently with the specification change.

**Comment by ewilligers** [comment]
Spec and tests allow unitless zero.
