### ISSUE TITLE
[filter-effects] blur() to take two parameters?

### ISSUE THREAD

**Issue by tomasdev** [w3c/fxtf-drafts#229]
There's nothing about this in the spec, but SVG blurring allows it to be on both X and Y axis, whereas the current spec and implementation of CSS blur() only allows a single value, to be applied to both axes.

*Example*: https://tympanus.net/codrops/2015/04/08/motion-blur-effect-svg/ stdDeviation can take  comma separated `x,y` values.
*Spec of SVG*: https://www.w3.org/TR/SVG/filters.html#feGaussianBlurStdDeviationAttribute

This would allow effects such as motion blur, useful particularly when mixing together with animations/transitions. Thoughts?

+@grorg 
+@erikdahlstrom 
+@dirkschulze

**Comment by dirkschulze** [comment]
@tomasdev A motion blur is a a blur towards a certain direction. That can not be done with either `blur()` or `<feGaussianBlur>`. However, I do agree that we should allow a 2nd value for `blur()` eventually in a 2nd version of the spec.

**Comment by tomasdev** [comment]
What I mean is feGaussianBlur currently does support it. https://codepen.io/tomasdev/pen/MrbQab

**Comment by dirkschulze** [comment]
@tomasdev Indeed and I suggest to add this into the next level of the spec. `blur()` ships in browsers w/ one value already and for this level it is more important to harmonize implementations and finalize level 1.
