### ISSUE TITLE
Update WebIDL definition(s) to use new mixin syntax

### ISSUE THREAD

**Issue by tobie** [w3c/fxtf-drafts#233]
Hi all!

WebIDL recently introduced [dedicated syntax for mixins][0].

This syntax replaces the `[NoInterfaceObject]` extended attribute and `implements statement` which have been deprecated (except for a few [legacy uses cases][1] explicitely mentioned in the spec).

You can read more about it [here][2].

In most cases, the changes should be relatively straightforward. The now deprecated:

```webidl
interface Foo { };

[NoInterfaceObject]  // (Mostly) DEPRECATED
interface Bar { };
Foo implementes Bar; // DEPRECATED
```

should just be rewritten as:

```webidl
interface Foo { };

interface mixin Bar { };
Foo includes Bar;
```

Additonaly, a section on [when to use partials and mixins][3] has been added to the spec. It's short and might be worth a read.

It seems the following interfaces in the [Geometry Interfaces Module Level 1](https://www.w3.org/TR/geometry-1/) spec are impacted by this change:

- [ ] DOMRectList

We're sorry for the inconvenience this causes, but our hope is that this ultimately makes things simpler and clearer for everybody.

As always, please feel free to reach out if you have any questions.

Thanks!

[0]: https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920
[1]: https://heycam.github.io/webidl/#NoInterfaceObject
[2]: https://heycam.github.io/webidl/#idl-interface-mixins
[3]: https://heycam.github.io/webidl/#using-mixins-and-partials

***

*Tracked in: heycam/webidl#472* | *Original pull-request: heycam/webidl#433*

**Comment by dirkschulze** [comment]
@tobie Do you know how good browser support is? Today, all browsers do use a WebIDL interpreter. Also, is there any immediate need to update the specs?

**Comment by tobie** [comment]
Browser support is in the works; you can check progress directly from heycam/webidl#472. 

About half of the specs have already moved to use mixins, hopefully the rest should follow rapidly.

**Comment by dirkschulze** [comment]
Thanks @tobie.

**Comment by dirkschulze** [comment]
@tobie I am not sure if `DOMRectList` qualifies for a mixin. I think the intention for it is just not to have an interface that a web developer can initiate with a "constructor" but I am unsure right now. I do not see any interface using it though. It must be specified somehow for `getClientRects()` IIRC.

**Comment by tobie** [comment]
You're right. Added it to the list of legacy interfaces in WebIDL (see https://github.com/heycam/webidl/pull/502).

**Comment by bzbarsky** [comment]
@dirkschulze Why is this interface `[NoInterfaceObject]` at all?  That's an antipattern, and one that doesn't seem to be needed for web compat, nor for future-compat (in that this is not a name anyone is likely to want to use for anything else).

Maybe this dates back to when people were trying to remove this interface and use sequences instead?  But if we've given up on that, we should just give it a normal interface object.

**Comment by dirkschulze** [comment]
@bzbarsky We investigated the usage at the time and it turned out that it is used far too often and in ways that made it impossible to use a sequence. (IIRC Blink or Gecko actually implemented it as sequence and had to revert the code.) As said, the strong request we got at the time was to make it at least impossible to reuse DOMRectList in other contexts but `getClientRects()`. I think the fear was that specifying DOMRectList makes it officially supported and may encourage developers or spec authors to reuse it despite the very visible warnings in the spec.

**Comment by TimothyGu** [comment]
I think the question is not whether it should be a separate interface, but rather why it shouldn’t have an interface object. Note that having an interface object doesn’t automatically make the interface constructable: you have to explicitly declare `[Constructor]` to do that. See e.g. HTML element classes: they are not (ordinarily) constructable yet they do have an interface object. 

We usually only use `[NoInterfaceObject]` for really special cases where it is necessary (like web compatibility or security concerns). The fact that Firefox is fine without the extended attribute is a sign that it is unnecessary.

**Comment by tobie** [comment]
Reopening this. It turns out that this interface should be kept as an interface but should have its [NoInterfaceObject] extended attribute removed.

**Comment by bzbarsky** [comment]
>  RESOLVED: Remove no itnerface object from geometry interface

This was resolved, and the spec changed, but the web platform tests were not updated... I guess I'll do that in https://bugzilla.mozilla.org/show_bug.cgi?id=1456887
