### ISSUE TITLE
Make textLength property on <text> and <tspan> a styleable property

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/fxtf-drafts#236]
https://svgwg.org/svg2-draft/single-page.html#text-TextElementTextLengthAttribute

This is a length value, and is likely to be used to make the length of a piece of text correspond to some other nearby geometry.  For example, a containing rectangle. Should this attribute be considered for inclusion in the list of styleable properties?

Plus there are other style related attributes that may have escaped consideration, such as fx, fy, markerWidth, markerHeight, orient, lengthAdjust etc.

Or at least should these be included on the list of attributes that "might be promoted in the future", similar to x1, y1, x2, y2 ?

**Comment by dirkschulze** [comment]
@BigBadaboom Could you please report SVG spec issues here https://github.com/w3c/svgwg/ ?

**Comment by js-choi** [comment]
Might [w3c/fxtf-drafts](//github.com/w3c/fxtf-drafts) be more appropriate for a CSS-in-SVG issue?

**Comment by BigBadaboom** [comment]
Apologies. I didn't realise I accidentally posted on fxtf.  Moved to https://github.com/w3c/svgwg/issues/375

**Comment by dirkschulze** [comment]
@BigBadaboom Thanks a lot!

@js-choi https://github.com/w3c/fxtf-drafts is for all FX specs hosted here (all FX specs but CSS Transforms). For all CSS and SVG specs you can find a link to the bug tracker in the header of the spec.
