### ISSUE TITLE
[filter-effects][css-masking] Should x,y,width,height on mask/filter elements map to SVG geometry properties?

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/fxtf-drafts#25]
I found a section of [SVG 2 draft](https://www.w3.org/TR/2015/WD-SVG2-20150915/styling.html#PresentationAttributes) describing the `x`,`y`,`width`,`height` attributes on the `mask` element as presentation attributes for the corresponding SVG [geometric properties](https://svgwg.org/svg2-draft/geometry.html).

I am removing that from SVG 2 because:
- it should really be defined in [CSS-Masking](https://drafts.fxtf.org/css-masking-1/#MaskElement)
- the defaults for a mask are different from the normal defaults for the properties, so there would need to be extra user agent stylesheet rules to set them
- whether or not these attributes should be CSS-controllable should be consistent between masks and filters (which use the same defaults and are somewhat conceptually similar)

That said, if there's a use case for defining mask (and filter) dimensions with CSS properties, all of these obstacles can be overcome.

For reference, similar attributes on SVG paint server elements are _not_ presentation attributes, and do not map to the geometry properties.

**Comment by dirkschulze** [comment]
In an SVG WG meeting we clarified that this will not be the case for any kind of resources. IIRC Some browsers like Firefox do not have those elements in the rendering tree and it is currently not possible to compute the value.

In addition, the inheritance model might be too confusing since the position of the resource in the document counts.

Until we clarified all criteria we deferred the promotion to presentation attributes.

**Comment by dirkschulze** [comment]
@AmeliaBR Are you ok with closing this issue or should we reevaluate this in a WG meeting?

**Comment by AmeliaBR** [comment]
Close, or defer to a future spec(s).

I do think that, once support for SVG geometry in CSS becomes widespread, we'll find author confusion for the elements that only support attributes. But it shouldn't delay Filters/Masking Level 1.

**Comment by dirkschulze** [comment]
@AmeliaBR Yes, that was discussed as well and I agree. I think we thought about incrementally supporting CSS properties in more places over time. Especially since implementers raised implementation complexity concerns.
