### ISSUE TITLE
[css-masking-1][filter-effects] Update definitions to take into account that `<use>` element is no longer a graphics element in SVG 2

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/fxtf-drafts#266]
`<use>` element is no longer defined as a graphics element in SVG 2. Therefore, CSS Masking and Filters specs must be adjusted so that any mention of SVG "graphics elements" is replaced with  "graphics elements and `<use>` element".

**Comment by dirkschulze** [comment]
Thanks! Change applied.
