### ISSUE TITLE
[css-masking-1] <clipPath> and <mask> elements are missing categories

### ISSUE THREAD

**Issue by SebastianZ** [w3c/fxtf-drafts#27]
The [Document Structure chapter of SVG 2 says](https://svgwg.org/svg2-draft/struct.html#TermContainerElement) `<clipPath>` is a container element and the [Rendering Model chapter says](https://svgwg.org/svg2-draft/render.html#TermNeverRenderedElement) it is a never-rendered element, though its [current definition](https://drafts.fxtf.org/css-masking-1/#ClipPathElement) does not list any categories.

Similarily, the [Rendering Model chapter says](https://svgwg.org/svg2-draft/render.html#TermNeverRenderedElement) `<mask>` is a never-rendered element, though its [current definition](https://drafts.fxtf.org/css-masking-1/#elementdef-mask) does only list _Container element_ as category.

Sebastian

**Comment by AmeliaBR** [comment]
Thanks.  Those categories were added to SVG 2 relatively recently, and this spec has not been updated to match.

**Comment by dirkschulze** [comment]
`<mask>` is already in the category "Container Elements" in the spec. `<clipPath>` is not yet. Will update the spec. Both are never-rendered elements though.

SVG2 does not seem to specify `never-rendered element` as an element category. Was it the intention to make it a category @AmeliaBR ?

**Comment by AmeliaBR** [comment]
@dirkschulze Depends what you mean by "element category".  In the sense of a category of elements that are used in other element's content model, no, it isn't used in that way.  But in the sense that it is used as a category in the element's blue-box definition, yes.  The definition is in the [rendering chapter](https://svgwg.org/svg2-draft/render.html#TermNeverRenderedElement).  We don't have a single location for defining other categories, they are scattered throughout the spec.

**Comment by dirkschulze** [comment]
@AmeliaBR ok, thanks.

**Comment by dirkschulze** [comment]
Fixed in https://github.com/w3c/fxtf-drafts/commit/5428abc4a2218b8d29686c877559f300fb8342ad

**Comment by SebastianZ** [comment]
Thanks for fixing this, Dirk!

Sebastian
