### ISSUE TITLE
[geometry] "When a user agent is asked to clone an DOMPoint..."

### ISSUE THREAD

**Issue by dirkschulze** [w3c/fxtf-drafts#273]
From @zcorpan on https://www.w3.org/Bugs/Public/show_bug.cgi?id=29556:

>https://drafts.fxtf.org/geometry/#cloning
>
>[[
>When a user agent is asked to clone an DOMPointReadOnly, DOMPoint, DOMRectReadOnly, DOMRect, DOMQuad, DOMMatrixReadOnly or DOMMatrix object >old, it must run the following steps, which return a new object of same type. These steps must be run atomically.
>
>Create a new object new of the same type as old. Copy all member variable values from old to new.
>Return new. It is the clone.
>The above algorithm follows the “safe passing of structured data” [HTML5] definitions.
>]]
>
>Need to update this section in terms of https://html.spec.whatwg.org/multipage/infrastructure.html#safe-passing-of-structured-data

**Comment by annevk** [comment]
Are these objects actually meant to be serializable so you can pass them to `postMessage()`? It seems they'd be rather useless in workers, no?

**Comment by zcorpan** [comment]
Yes. Why are they useless? DOMMatrix can be used with offscreen canvas (`setTransform` and `addPath`).

This issue is fixed by the way in https://github.com/w3c/fxtf-drafts/commit/582844c27b009c1144d5d47676c0dcd54182983b#diff-ed7daeb157cd9b31e53896ad3c771a26 , so closing.

**Comment by annevk** [comment]
Fair enough I suppose.
