### ISSUE TITLE
Investigate removing [LegacyArrayClass] from DOMRectList

### ISSUE THREAD

**Issue by annevk** [w3c/fxtf-drafts#280]
It seems that as of https://github.com/heycam/webidl/pull/550 it might be the last class in the web platform to have it.

cc @emilio @tobie @marcoscaceres @bzbarsky

**Comment by dirkschulze** [comment]
Here are some pointers to DOMRectList: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26200

**Comment by dirkschulze** [comment]
Here some user data: https://www.chromestatus.com/metrics/feature/timeline/popularity/694

**Comment by dirkschulze** [comment]
Some more links to this topic:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23682
https://bugs.webkit.org/show_bug.cgi?id=81573
https://www.w3.org/Bugs/Public/show_bug.cgi?id=16490

**Comment by csnardi** [comment]
It looks like neither [WebKit](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/dom/DOMRectList.idl) nor [Chrome](https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/core/geometry/dom_rect_list.idl) implements as a `[LegacyArrayClass]`, but [Firefox](https://dxr.mozilla.org/mozilla-central/source/dom/webidl/DOMRectList.webidl) does. Edge doesn't appear to implement the IDL specified in Geometry.

**Comment by bzbarsky** [comment]
@dstorey no one except Edge was implementing those, so they were removed from the spec.  See https://github.com/w3c/csswg-drafts/issues/2601

**Comment by dstorey** [comment]
@bzbarsky I'll look to see if I can do a PR to remove it in Edge. We also have it on StyleSheetPageList, but as far as I can see that isn't in any standard and is from the IE8 era.

**Comment by annevk** [comment]
As far as I can tell WebKit does not have it (inspecting the return value of `document.body.getClientRects()`). Let's remove this one too.

**Comment by annevk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1456887.

**Comment by dirkschulze** [comment]
@annevk Just to clarify: Simply removing `[LegacyArrayClass]` means that `DOMRectList` will just provide the `length` read-only attribute and the `item()` method. Authors won't be able to use Array methods.

Currently, only Firefox seems to allow Array functions. So following your suggestion unlikely breaks web content. And looking at the activity on the referenced Mozilla bug, Mozilla seems to be on board with removing `[LegacyArrayClass]`.

So I'll go ahead and remove it from the spec.

**Comment by annevk** [comment]
Yeah, I think one thing we can consider is adding an `iterable<>` declaration at some point, but I'd really like to make `[LegacyArrayClass]` disappear as it just didn't really work out well and was always a bit of a hack.
