### ISSUE TITLE
[filter-effects-1] update flood-opacity to use <alpha-value>

### ISSUE THREAD

**Issue by dstorey** [w3c/fxtf-drafts#284]
The definition for [flood-opacity](https://drafts.fxtf.org/filter-effects/#FloodOpacityProperty) uses `<number-percentage>` from CSS Values L4
Other opacity use `<alpha-value>` from [CSS Colour L4](https://drafts.csswg.org/css-color/#typedef-alpha-value). The is similar but clamps the useful range to be between 0 and 1.

We've [just made this change in SVG](https://github.com/w3c/svgwg/pull/432).

CC @dirkschulze

**Comment by dirkschulze** [comment]
@dstorey Hm. `flood-opacity` used to have `<opcacity-value>` which used to be `<number>`. The spec did change this to `<number-percentage>` at some point. Is there a WG resolution to support `<percentage>` as well?

No browser supports the `<percentage>` value. Ditto for `fill-opacity` by the way.

**Comment by dstorey** [comment]
@AmeliaBR mentioned on the SVG issue that there was already a WG resolution and the values were number | percentage. The decision predated my time.

Judging by the state of the test suite, I expect there isn't any tests, but there could have been some when the original change was made. Part of our CR efforts is to write tests for changes since 1.1. If there is an entry in the change log for the original change then the tests will be written at some point. We probably want to write them similar than any CSS opacity tests for percentage values. I'm not sure if there is an existing pattern or not like the interface.html tests for WebIDL.

**Comment by dstorey** [comment]
I did a quick test with https://jsfiddle.net/hgovsx13/ and no browser supports percentages. The test folder linked (nor any directly linked via the CSS 3 Colour spec) don't test percentages.

I'm fine with keeping the change for now to be consistent with CSS 4 Colour, with an eye on reverting it if they revert back to CSS 3 behaviour. As Amelia mentioned, all opacity properties should be updated at the same time (or rejected if browsers don't want to do it). I guess whichever of the 3 specs goes to rec first can figure that out.

**Comment by dirkschulze** [comment]
@dstorey @AmeliaBR Couldn't remember that we made such resolution already. Am fine with doing the change. Just hold back since no browser supported percentage for any of the `*-opacity` properties.
