### ISSUE TITLE
[filter-effects-1] Interaction of color-interpolation-filters and CSS url() filter function is ill defined

### ISSUE THREAD

**Issue by smfr** [w3c/fxtf-drafts#285]
It's not really clear from the spec how `color-interpolation-filters` and `filter: url(#foo)` interact.

color-interpolation-filters has a note:
> Note: The color-interpolation-filters property has no affect on Filter Functions, which operate in the sRGB color space.

and color-interpolation-filters is denoted as:
> Applies to: All filter primitives

so what happens with:

```
<svg><defs>
  <filter id="foo"  color-interpolation-filters="sRGB">
    <feColorMatrix type="saturate" values="3"/>
  </filter>
</defs></svg>
<div style="filter: url(#foo)"></div>

```

What Gecko and Blink do is use the value of color-interpolation-filters on the filter primitives, defaulting to linearRGB, which is probably correct. Seems that WebKit always uses linearRGB, which is not.

**Comment by svgeesus** [comment]
> What Gecko and Blink do is use the value of color-interpolation-filters on the filter primitives, defaulting to linearRGB, which is probably correct.

Yes.

>> Note: The color-interpolation-filters property has no affect on Filter Functions, which operate in the sRGB color space.

I am not sure why or by whom that was added.

**Comment by dirkschulze** [comment]
@smfr @svgeesus There is a clear distinguishing between Filter Primitives and Filter Functions in the spec.

Filter Primitives are the elements you are referring to like `<feBlend>` and Filter Functions are the functions applied on the property like `saturate(50%)`. The latter does not include `url()`.

**Comment by smfr** [comment]
> The latter does not include url()
But url() is listed under https://drafts.fxtf.org/filter-effects/#filter-functions and is, strictly speaking, a function in CSS syntax.

**Comment by dirkschulze** [comment]
Renamed filter-function-list to filter-value-list. Moved out url() from Filter Functions definition section. Hope this helps making the difference to filter primitives a bit more obvious. Otherwise, let me know.
