### ISSUE TITLE
[filter-effects-1] Saturate filter function definition is wrong

### ISSUE THREAD

**Issue by smfr** [w3c/fxtf-drafts#286]
https://drafts.fxtf.org/filter-effects/#saturateEquivalent says that the saturate() equivalent is:
```
<filter id="saturate">
  <feColorMatrix type="saturate" values="(1 - [amount])"/>
</filter>
```

I think that should be `  <feColorMatrix type="saturate" values="[amount]"/>
`

**Comment by dirkschulze** [comment]
Confirmed: https://codepen.io/krit/pen/wjpwmq
