### ISSUE TITLE
Current Transform Matrix (CTM) setup to not export

### ISSUE THREAD

**Issue by dstorey** [w3c/fxtf-drafts#289]
In SVG we are referencing CTM:

```
  <term name='CTM' href='https://www.w3.org/TR/css-transforms-1/#current-transformation-matrix'/>
  <term name='current transformation matrix' href='https://www.w3.org/TR/css-transforms-1/#current-transformation-matrix'/>
```

We get lint errors as this term is set to noexport in CSS Transforms:

```
<dfn class="dfn-paneled" id="current-transformation-matrix" data-noexport="" data-dfn-type="dfn">current transformation matrix</dfn>
```
 
https://drafts.csswg.org/css-transforms/#current-transformation-matrix

Is it possible to change this to data-export or is there a reason why it is noexport?

**Comment by dstorey** [comment]
CC @dirkschulze 
P.S. there doesn't seems to be a CSS transforms label listed.

**Comment by dirkschulze** [comment]
@dstorey Could you reopen this issue in the csswg-draft repo on https://github.com/w3c/csswg-drafts please?

I know it is confusing that the FXTF spec is hosted in the CSSWG.

**Comment by dstorey** [comment]
Sure. Do you want a bug for changing the github link in the pc to csswg too?

**Comment by dstorey** [comment]
Thanks. When we make our next change to the spec I'll check the link warning mail and close when it passes.
