### ISSUE TITLE
ed's affiliation needs updated

### ISSUE THREAD

**Issue by gsnedders** [w3c/fxtf-drafts#290]
@erikdahlstrom hasn't worked at Opera Software ASA for a while (and Opera Software ASA no longer develops a browser and is now  called Otello Corporation ASA).

**Comment by dirkschulze** [comment]
@gsnedders I don't think @erikdahlstrom has any affiliation to any of the W3C members anymore. So he probably should move to the former editor list or request to get an invited expert.

**Comment by gsnedders** [comment]
@dirkschulze He's at MS now, AFAIK, who obvious are a Member. Regardless, as pubrules says:

> If an editor/author is acknowledged in an earlier version of this document and the individual's affiliation has since changed, list the individual using the notation "<name>, <affiliation> (until DD Month YYYY)"

That said, I agree with @AmeliaBR that he should probably just move to Former Editors, unless he objects.
