### ISSUE TITLE
Various Editor's Drafts have disappeared from drafts.fxtf.org

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/fxtf-drafts#297]
I'm not sure what happened, or how many specs are affected. Filter Effects is no longer available, with no redirect. Compositing and Masking lead to auto-generated folder indexes.

https://drafts.fxtf.org/

**Comment by ewilligers** [comment]
There was an observation during the CSS WG that pull requests on the
generated .html are being received, and that we shouldn't have checked in
generated HTML in the repo.

I thus sent 4 pull requests deleting generated Overview.html files where
there were Overview.bs files - 1 fxtf and three css-wg.  (Numbers from
memory.)

We'll check why the site isn't serving generated files.

**Comment by astearns** [comment]
Hopefully should be fixed now.
