### ISSUE TITLE
[motion-path] Remove <size> from offset-distance and add <size> to offset-path

### ISSUE THREAD

**Issue by jihyerish** [w3c/fxtf-drafts#30]
I found that < size > seems to be meaningless for offset-distance.

Instead, how about adding < size > to offset-path and make it be used only with < angle >?
Then < size > can decide the end point of the path.
For now, when the path is specified with < angle >, the path starts from the current position of the path and ends when it meets the edges of the containing block.

So, the values of offset-path
should be
	< url > | < angle > < size >? && contain? | [ < basic-shape > | < path() > ] || < geometry-box > | none

**Comment by jihyerish** [comment]
@shans What are your views on this?

**Comment by shans** [comment]
I think this is a good change.

**Comment by jihyerish** [comment]
Thanks! I updated the spec with this change.
