### ISSUE TITLE
[css-transforms-2] How to serialize `scale` if we only use one number?

### ISSUE THREAD

**Issue by BorisChiou** [w3c/fxtf-drafts#313]
The spec [1] doesn't mention how to serialize the individual transforms. This may be fine but still not clear to me for the case:
```
div { 
  scale: 2;
}
console.log(window.getComputedStyle(div).scale); // serialize as "2" or "2 2"?
```
If only the X value is given, the Y value defaults to the same value, and If one or two values are given, this specifies a 2d scaling, equivalent to the `scale()` function (i.e. scale(2, 2) in the above example). However, should we serialize it as "2" or "2 2"? For now, Chrome serializes this as "2 2", but Firefox serializes this as "2", so I think this is an ambiguous part. Maybe the shorter one is preferred?

[1] https://drafts.csswg.org/css-transforms-2/#propdef-rotate

**Comment by tabatkins** [comment]
Via the standard "prefer shorter serializations when possible" principle, `2` should be the preferred serialization.

**Comment by BorisChiou** [comment]
Thanks for this. :).

Actually, there is another question for this. If we use 3 numbers, but the last one is "1",
e.g.
```
scale: 2 2 1;
```
Chrome and Firefox serialize this as `2 2`, instead of `2 2 1`. This is also because "prefer shorter serializations when possible"? Using 3 numbers means you want to use it as `scale3d()`. However, if we serialize it as `2 2`, this may be pretty hard to understand the intention of the author. Anyway, either way is ok to me.

**Comment by tabatkins** [comment]
Sigh. That's a Chrome bug. `2 2 1` does indeed signal a 3d transform, which has side-effects and is not equivalent to `2 2`.

**Comment by BorisChiou** [comment]
Thanks a lot. :)

**Comment by tabatkins** [comment]
Reported at <https://bugs.chromium.org/p/chromium/issues/detail?id=901509>

**Comment by ewilligers** [comment]
Suppose we are animating `scale` from "2 1" to "2 3". At the animation midpoint, should the `getComputedStyle()` output have a discontinuity with "2" instead of "2 2" ? I suggest not. Similarly, I would suggest that changing the specified value from "2" to "2 2" should not trigger a transition. Therefore I would suggest that `getComputedStyle()` always return two numbers (or three if we have a 3D scale).

For the specified value, I would suggest avoiding discontinuities by returning exactly as many numbers as were supplied. Thus my suggestion is "2" stays "2" and "2 2" stays "2 2".

The same arguments apply for `translate`.

> `scale: 2 2 1;`
> Chrome and Firefox serialize this as `2 2`, instead of `2 2 1`.

Implementation(s) and WPT predate the [spec change](https://github.com/w3c/csswg-drafts/commit/48f19e8c923115af8334594a0ee79fb342c2a731#diff-7a1256a4a031b8446dd0fba783bfe17d) about 2d or 3d scaling. As Tab points out, it should be `2 2 1`.

**Comment by heycam** [comment]
> Suppose we are animating `scale` from "2 1" to "2 3". At the animation midpoint, should the `getComputedStyle()` output have a discontinuity with "2" instead of "2 2" ? I suggest not. Similarly, I would suggest that changing the specified value from "2" to "2 2" should not trigger a transition. Therefore I would suggest that `getComputedStyle()` always return two numbers (or three if we have a 3D scale).

Yes, I don't think it makes sense for "2" and "2 2" to be different values either in the specified or computed value space.

> For the specified value, I would suggest avoiding discontinuities by returning exactly as many numbers as were supplied. Thus my suggestion is "2" stays "2" and "2 2" stays "2 2".

I don't think discontinuities in the animated (computed) value are impacted by how we decide to serialize the specified value.

In any case, these arguments seem applicable to any property that supports continuous interpolation and has optional/implied values in it, but it's at odds with the current guidelines in CSSOM.  I would rather update those guidelines if we want to avoid discontinuities while animating, rather than deciding just for scale/translate.

**Comment by tabatkins** [comment]
> At the animation midpoint, should the getComputedStyle() output have a discontinuity with "2" instead of "2 2" ? I suggest not.

That is indeed what our current guidelines suggest. If we want to change that (to take animation into account, such that things aren't omitted if they're an animatable type and some of their values wouldn't be omitted), that sounds reasonable, but we need to get that figured out and written down. ^_^

**Comment by tabatkins** [comment]
> Similarly, I would suggest that changing the specified value from "2" to "2 2" should not trigger a transition.

Non sequitur here, tho. This is about how to serialize a value. That has nothing to do with the actual computed value, which should indeed always be 2 or 3 values. (And needs proper specifying.) Serialization is a completely unrelated topic from transition triggers.

**Comment by tabatkins** [comment]
Yup, that definitely needs fixing.

**Comment by tabatkins** [comment]
Okay, I've fixed the computed values to be clearer about what they are in each case, and specified serialization: https://drafts.csswg.org/css-transforms-2/#individual-transforms

**Comment by ewilligers** [comment]
In the serialization [change](https://github.com/w3c/csswg-drafts/commit/b20199391df43f84fca8de9026775389e043f8c7#diff-7a1256a4a031b8446dd0fba783bfe17d)

> if the second value is ''0px'', the default, it must be omitted when serializing

Are `0` or `0em` omitted?

> if the second value is the same as the first, the default, it must be omitted when serializing

Suppose we have a calc expression. Is `calc(2 * 3)` the same as `calc(3 * 2)`? Is `calc(--foo * --bar)` the same as `calc(--bar * --foo)`? Do we have a definition for calc sameness?

> If a 3d rotation is specified, the property must serialize with an axis specified. If the axis is parallel with the x, y, or z axises, it must serialize as the appropriate keyword.

This may require evaluation of calc expressions, and perhaps reversal of the angle.

**Comment by ewilligers** [comment]
The relevant WPT will be [css-transforms/parsing/rotate-parsing-valid.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-transforms/parsing/rotate-parsing-valid.html) etc.

**Comment by tabatkins** [comment]
> Are 0 or 0em omitted?

This is a computed value, so it's already absolutized and canonicalized.

> Suppose we have a calc expression.

Ditto.

> This may require evaluation of calc expressions,

Ditto.

> and perhaps reversal of the angle.

Parallel, not anti-parallel.

**Comment by BorisChiou** [comment]
> Sigh. That's a Chrome bug. `2 2 1` does indeed signal a 3d transform, which has side-effects and is not equivalent to `2 2`.

@tabatkins Sorry to ask the question here, but I still want to know why the 3d transform has the side-effects and not equal to the 2d?
e.g.
`translate: 10px 10px 0px` vs `translate: 10px 10px`, and
`scale: 2 2 1` vs `scale: 2 2`,
I thought they are the same, but as you mentioned, the 3d version is actually different and has side-effects. Would you mind to give me more explanation or is there any reference? Thank you very much.

**Comment by tabatkins** [comment]
Implementations cause 3d transforms to put the element on a separate "rendering layer" from the rest of the page, so it can be transformed and composited by the existing fast 3d code in their graphics libraries.

Thus the classic `translateZ(0)` hack, which has some useful side-effects despite not actually moving the element at all.

**Comment by birtles** [comment]
I believe that's WebKit/Blink specific behavior. `translateZ(0)` does not trigger layer creation in Gecko (hence why we introduced `will-change`--to give authors a cross-browser way of achieving that optimization).

I wonder if it's necessary to preserve that quirk with the individual transform properties?

**Comment by BorisChiou** [comment]
Thanks for these explanations. :)

**Comment by birtles** [comment]
Yeah, in Firefox you had to use `transform: translateZ(1px)` (as described back [in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=940842#c0) where Benoit first began experimenting with [will-animate](https://lists.w3.org/Archives/Public/www-style/2013Nov/0414.html)).
