### ISSUE TITLE
[filters-1] Add animation type to properties

### ISSUE THREAD

**Issue by SebastianZ** [w3c/fxtf-drafts#32]
As mentioned in the [www-style mailing list](https://lists.w3.org/Archives/Public/www-style/2016May/0121.html) and [Bikeshed](https://github.com/tabatkins/bikeshed/blob/8baea9dda4436e4c925616444d4ee3f6ac9a1ea3/docs/markup.md#propertydescriptorelement-definition-table-expansion), 'Animatable' should get replaced by an 'Animation type'.

The Filters module currently only says 'yes' for the animatable properties. So, by changing to 'Animation type' it needs to be specified _how_ they are animated.

Sebastian

**Comment by dirkschulze** [comment]
@birtles Your referenced mail above seems to look at CSS properties specifically. Did we agree to do the same for SVG element attributes?

**Comment by birtles** [comment]
What's the context? Specifically, what non-presentation-attributes are we dealing with?

In any case, yes, animation type makes sense although I don't think there's any resolution to that effect.

**Comment by AmeliaBR** [comment]
@birtles For the filters spec, there are all sorts of non-CSS attributes to filter-related elements that are animatable under SMIL/WAAPI.

However, unlike with CSS there isn't agreement that "everything is animatable" when it comes to attributes.  Looking at the spec, I don't see a lot of "animatable: no" mentions, but some attributes don't specify it either way.  I can't imagine animating the `result` name of a filter primitive, for example.  For the data types of animatable attributes, there were standard rules for how to interpolate in SVG 1.1, currently located [in the animation elements spec](https://svgwg.org/specs/animations/#AnimationAttributesAndProperties).

**Comment by birtles** [comment]
e.g. `<feBlend>`'s `in2` attribute? Yeah, that's a bit awkward. There's no standard definition of 'discrete' animation that applies to attributes since Web Animations now specifically supports CSS property animation only.

Part of the reason SVG has `animatable: yet` so often is because of `<set>` animations (i.e. you trigger certain things to happen at different times in a sequence).

Maybe you're best off to just reference SVG 1.1. Any maybe 'yes' is fine for these attributes.

**Comment by dirkschulze** [comment]
@AmeliaBR I checked again and just `crossorigin` didn't define animate support. Fixed now.

**Comment by SebastianZ** [comment]
For reference, my initial comment only referred to the [CSS properties defined in that spec.](https://drafts.fxtf.org/filters-1/#property-index), which currently also just say yes or no.

For the non-presentation-attributes I guess it's fine to refer to the SVG 1.1 or the SVG Animations spec.

Sebastian
