### ISSUE TITLE
[css-motion] offset-path animation can be more general

### ISSUE THREAD

**Issue by ewilligers** [w3c/fxtf-drafts#33]
offset-path currently only allows angle to be animated. But [shape-outside](https://drafts.csswg.org/css-shapes-1/#shape-outside-property) allows basic-shape to be animated, and [d](https://svgwg.org/svg2-draft/paths.html#DProperty) allows path to be animated.

offset-path could similarly allow these to be animated.

**Comment by jihyerish** [comment]
I agree that offset-path could animate with < basic-shape >, but not sure about allowing < path() >.

**Comment by shans** [comment]
This is an existing capability of SVG. Essentially, the algorithm is:

1) match segments from the 'from' path to the 'to' path
2) interpolate the control points of each segment pair
3) perform the offset computation on the interpolated path

Unfortunately this isn't the ideal approach as it doesn't deal with mismatched paths, but it's a lot better than no animation behavior.

**Comment by jihyerish** [comment]
Thanks for the explanation. Then it seem to be good to change.
