### ISSUE TITLE
[motion-1] Make sure the used offset distance is positive in closed loop

### ISSUE THREAD

**Issue by BorisChiou** [w3c/fxtf-drafts#339]
We calculate the `used offset distance` by the steps defined in [1]. For a closed loop, the spec says:
> Let used offset distance be equal to offset distance modulus the total length of the path. If the total length of the path is 0, used offset distance is also 0.

Perhaps it'd be better to mention that the `used offset distance` should be equal to or larger than 0 in this case. (Though this may just depend on the implementation detail.)
Note: Chromium did it [2], and Firefox will follow this idea as well [3].

[1] https://drafts.fxtf.org/motion-1/#calculating-the-computed-distance-along-a-path
[2] https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/style/computed_style.cc?l=1207-1208&rcl=ebc261685e926af961bb12a34cd04ae7dec35182
[3] https://bugzilla.mozilla.org/show_bug.cgi?id=1429299

cc @birtles @ericwilligers

**Comment by ewilligers** [comment]
I don't think of modulus being non-negative as an implementation detail, rather part of the traditional mathematical definition, e.g. https://en.wikipedia.org/wiki/Euclidean_division or http://mathworld.wolfram.com/CommonResidue.html.

I have uploaded a [WPT](https://github.com/web-platform-tests/wpt/pull/16835). It is already covered by spec example 6 (Figure 9). No objection to adding a note.

**Comment by birtles** [comment]
I'm probably not following, but it's not what ECMAScript '%' gives you, e.g. `-120 % 50` gives -20, but I believe the desired result here is 30 (assuming the used distance is supposed to be within the range of the path distance). Likewise for `fmod`.

**Comment by BorisChiou** [comment]
Ya. It seems adding a note for this may be great. :)
