### ISSUE TITLE
[geometry] DOMMatrix scaleSelf() step 6 has a redundant originZ check

### ISSUE THREAD

**Issue by saschanaz** [w3c/fxtf-drafts#350]
https://drafts.fxtf.org/geometry/#dom-dommatrix-scaleself

`scaleSelf()` step 6 says:

>If _scaleZ_ is not 1 or _originZ_ is not 0 or -0, set is 2D of the current matrix to false.

But the originZ check is redundant because `scaleSelf()` internally calls `translateSelf()` in step 1 which does that check already.

I think we can remove the check, thoughts?

cc @bzbarsky

**Comment by dirkschulze** [comment]
@saschanaz You mean

> or originZ is not 0 or -0

can be removed? Agree, should have been done by `translateSelf()`.

**Comment by saschanaz** [comment]
Filed #351 🚅
