### ISSUE TITLE
[geometry] Update to constructor operations

### ISSUE THREAD

**Issue by Ms2ger** [w3c/fxtf-drafts#367]
See https://github.com/heycam/webidl/issues/778.

**Comment by dirkschulze** [comment]
@Ms2ger could you please confirm that the change (taking `DOMMatrixReadOnly` as example) would be correct?

```diff
-[Constructor(optional (DOMString or sequence<unrestricted double>) init),
- Exposed=(Window,Worker),
- Serializable]
-interface DOMMatrixReadOnly {
+[Exposed=(Window,Worker),
+ Serializable]
+interface DOMMatrixReadOnly {
+ constructor(optional (DOMString or sequence<unrestricted double>) init)
```

**Comment by Ms2ger** [comment]
Yes, looks good. Thank you!

**Comment by dirkschulze** [comment]
Created a PR for the requested changes here: https://github.com/w3c/fxtf-drafts/pull/373. However, with this change the links in the spec are broken. I'd like to wait for fixes in Bikeshed before landing the PR.

Bikeshed issue for reference: https://github.com/tabatkins/bikeshed/issues/1521
