### ISSUE TITLE
[css-motion] Computed value of distance properties

### ISSUE THREAD

**Issue by ewilligers** [w3c/fxtf-drafts#37]
[offset-distance](https://drafts.fxtf.org/motion-1/#offset-distance-property), [offset-position](https://drafts.fxtf.org/motion-1/#offset-position-property) and [offset-anchor](https://drafts.fxtf.org/motion-1/#offset-anchor-property) each state:
"Computed value:	as specified"

"as specified" would suggest that the computed value of offset-distance can be 'auto', which is inconsistent with "Computes to the current position of the element."

It would also suggest the computed value can contain a variety of units, such as em, instead of pixels and percentages.

For comparison, [perspective-origin](https://www.w3.org/TR/css-transforms-1/#perspective-origin-property) and [transform-origin](https://www.w3.org/TR/css-transforms-1/#transform-origin-property) have
Computed value:	For <length> the absolute value, otherwise a percentage.

[background-position](https://www.w3.org/TR/css3-background/#the-background-position) has
... a pair of offsets (horizontal and vertical) from the top left origin each given as a combination of an absolute length and a percentage

**Comment by jihyerish** [comment]
This change makes clear definitions.
