### ISSUE TITLE
[css-masking] mask-border-mode in mask-border grammar

### ISSUE THREAD

**Issue by ewilligers** [w3c/fxtf-drafts#378]
mask-border

> is a shorthand property for setting mask-border-source, mask-border-slice, mask-border-width, mask-border-outset and mask-border-repeat. Omitted values are set to their initial values.
>
> Note: The mask shorthand resets the properties mask-border, mask-border-source, mask-border-mode, mask-border-slice, mask-border-width, mask-border-outset and mask-border-repeat.

This suggests that [`mask-border`](https://drafts.fxtf.org/css-masking-1/#the-mask-border) does not set `mask-border-mode`, and that [`mask-border-mode`](https://drafts.fxtf.org/css-masking-1/#propdef-mask-border-mode) is the only additional longhand that [`mask`](https://drafts.fxtf.org/css-masking-1/#the-mask) sets.

However, the grammar for mask-border ends with `|| <'mask-border-mode'>`.

Does this imply that `luminance | alpha` is permitted, but discarded?

**Comment by dirkschulze** [comment]
@ewilligers This just seems to be an oversight since `mask-border-mode` was added later. As you said, the grammar lists `mask-border-mode`.
