### ISSUE TITLE
[motion-1] The computed value of offset-path: path(' ')

### ISSUE THREAD

**Issue by BorisChiou** [w3c/fxtf-drafts#392]
Based on the definition of SVG1.1 and [SVG2](https://svgwg.org/svg2-draft/paths.html#PathDataBNF):
> The EBNF allows the path data string in the d property to be empty. An empty path data string disables rendering of the path. Rendering is also disabled when the d property has the value none.

So an empty path string is valid. And then what is the expected computed value for this case?
```
offset-path: path(' ');
```
If someone calls `getComputedStyle(div).offsetPath`, should we return `path('')` or `none` for `offset-path`? It seems Blinks return `none` for now. It looks like the [spec](https://drafts.fxtf.org/motion-1/#offsetpath-pathfunc) doesn't mention this, anyway.

**Comment by BorisChiou** [comment]
cc @ericwilligers

**Comment by ewilligers** [comment]
Blink treats `<path d=""/>` and `<path />` and `<path style="d: path('')" />` and `<path style="d: none" />` all as having path `none` - [example](https://jsfiddle.net/ericwilligers/jys1vLhk/). 

I don't see value in maintaining different computed style states for these.

The spec could state that `path()` with an empty path string serializes as `none`.

**Comment by BorisChiou** [comment]
Great. Thanks. This is also for `clip-path`. I'm also updating Gecko to have `none` value for `clip-path: path(' ')`.

**Comment by emilio** [comment]
It seems really odd to serialize it as `none` but parse it as valid. It seems to me that `path('')` is a fine path, just with no commands...

**Comment by ewilligers** [comment]
>  It seems to me that `path('')` is a fine path, just with no commands..

It is, that is why in the [example](https://jsfiddle.net/ericwilligers/jys1vLhk/) it sets the specified value, while `path('nonsense')` does not. This is about normalization: no commands is equivalent to no path.

**Comment by emilio** [comment]
But they're not the same, right? `offset-path: path('')` should establish a containing block and so on. It's just not equivalent to `none` the same way as `transform: translate(0)` is not equivalent to `transform: none`.
