### ISSUE TITLE
Replace <shape-arg> with <length-percentage>

### ISSUE THREAD

**Issue by jwatt** [w3c/fxtf-drafts#4]
CSS Values and Units 3 now has [`<length-percentage>`](https://drafts.csswg.org/css-values-3/#typedef-length-percentage). The [`<shape-arg>`](https://drafts.csswg.org/css-shapes-1/#typedef-shape-arg) type could be dropped from CSS Shapes Module Level 1 and replaced with `<length-percentage>`.

The same applies for other instances of `<length> | <percentage>` in that spec.

**Comment by jwatt** [comment]
And occurrences where the order of appearance is reversed: `<percentage> | <length>`.

**Comment by dirkschulze** [comment]
@jwatt Is this in general for FXTF specs or specific to CSS Shapes? (The latter is not a cooperation of CSS WG and SVG WG but a pure CSS WG spec.)

**Comment by jwatt** [comment]
I'm not sure why it matters, but I had only been looking at CSS Shapes so it was the text of that spec that I was suggesting fixing up.

**Comment by jwatt** [comment]
Oh, I see, you mean this issue is filed in the wrong place?
