### ISSUE TITLE
change text color with mix-blend-mode when divs are overlapping

### ISSUE THREAD

**Issue by sohailrahimi** [w3c/fxtf-drafts#401]
I have a circular div which follows my cursor. When this div overlaps some text on my page, I want the color of the text to change. I know this is possible with mix-blend-mode like in this Fiddle, but I just can't get it to work. I tried backdrop-filter and different approaches with SVG but none of it will work. I've seen this effect on so many sites, but I just can't figure it out myself.

**Comment by astearns** [comment]
@sohailrahimi this repository is for work on the specifications, not general help with writing code. You'll have better luck googling for an answer or asking on a coding forum.
