### ISSUE TITLE
[motion-1] Invalid offset-path value syntax

### ISSUE THREAD

**Issue by pyoor** [w3c/fxtf-drafts#410]
The `ray()` and `path()` functions in the `offset-path` value definition must be wrapped in `<>` to identify them as CSS types.

https://github.com/w3c/fxtf-drafts/blob/cb4c0bb766ccc4a6670c240107c934865389089c/motion-1/Overview.bs#L106

The correct syntax should be:
`none | <ray()> | <path()> | <url> | [ <basic-shape> && <coord-box>? ] | <coord-box>`

**Comment by jihyerish** [comment]
I think you're right. I couldn't find the exact guide of value definition syntax for functional values in https://drafts.csswg.org/css-values-3/#value-defs.
But most of the functional values such as url(), *-gradient() are wrapped in <>.

**Comment by SebastianZ** [comment]
The definition in https://drafts.csswg.org/css-values-4/#component-types (note that level 4 is the current version worked on) doesn't explicitly mention how functional values have to look like, i.e. it doesn't say that their names need to be followed by some parentheses. Though as their definition is somewhere else, they are non-terminal values. And by that they are required to be surrounded by `<` and `>`.

Bikeshed also has a note about that at https://tabatkins.github.io/bikeshed/#autolink-wrappers.

Sebastian
