### ISSUE TITLE
Changes to this repo are not getting deployed

### ISSUE THREAD

**Issue by foolip** [w3c/fxtf-drafts#424]
I recently sent https://github.com/w3c/fxtf-drafts/pull/421 + https://github.com/w3c/fxtf-drafts/pull/422 which @tabatkins merged, but https://drafts.fxtf.org/filter-effects/ is not getting updated. There's no apparent CI setup in the repo itself, so presumably there's some extra step to deploy.

Who can help do that? Can it be automated?

**Comment by tabatkins** [comment]
Hm, all the fxtf specs should be covered by the same private CI (run by @plinss) that the CSSWG and Houdini specs are, afaik.

**Comment by foolip** [comment]
@dontcallmedom might this be the same issue with the `master` branch?

**Comment by dontcallmedom** [comment]
I've pushed a merge of `main` into `master`, but it doesn't seem to suffice here (compared to https://github.com/w3c/svgwg/issues/843 for reference) - @plinss help?

**Comment by plinss** [comment]
That's because there's a filter-effects/Overview.html file in the repo, which overrides the auto-generation. Delete it and auto-generation will take over.

We should also delete the master branch.
