### ISSUE TITLE
Republish masking-1 as CR Draft

### ISSUE THREAD

**Issue by svgeesus** [w3c/fxtf-drafts#431]
Although there are [quite a few open issues](https://github.com/w3c/fxtf-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-masking-1) and not much activity since 2019, there have been [substantial edits](https://github.com/w3c/fxtf-drafts/commits/main/css-masking-1/Overview.bs) to masking-1 since [the last /TR publication in **2014**](https://drafts.fxtf.org/css-masking-1/).

The [test suite results](https://test.csswg.org/harness/results/css-masking-1_dev/grouped/) show that the spec is implemented.

So it seems that at least, a new /TR publication should be done, with the spec we have now, as a CR draft.

Wide review should also be started, as review procedures have changed a fair bit since 2014, so we can then publish a CR Snapshot

@dirkschulze @birtles @tabatkins

**Comment by dirkschulze** [comment]
@svgeesu I'll try to fix the most pressing spec building errors.

**Comment by dirkschulze** [comment]
@svgeesus done. Could I ask you to start the process please?

**Comment by svgeesus** [comment]
Started  issue to [track wide review of masking-1](https://github.com/w3c/fxtf-drafts/issues/432)

**Comment by svgeesus** [comment]
[Changes since 2014 CR](https://drafts.fxtf.org/css-masking-1/#changes)

**Comment by svgeesus** [comment]
@astearns @atanassov Agenda+ to request publication as **CR Draft**. Wide review should also be started, once that is published.

**Comment by svgeesus** [comment]
@dirkschulze Thanks for the cleanup! (I noticed a couple of missing images in example 6).

**Comment by svgeesus** [comment]
CRD [published 5 Aug 2021](https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/)
