### ISSUE TITLE
[css-masking-1] clarification of grammar regarding validity of <geometry-box> on mask-origin and mask-clip

### ISSUE THREAD

**Issue by jimmylewis** [w3c/fxtf-drafts#439]
In the [Changes](https://www.w3.org/TR/css-masking-1/#changes) section comparing to the 26 August 2014 version, it mentions:
> Remove margin-box as possible value from mask-origin and mask-clip.

The grammar for these properties is still defined as `<geometry-box>#` and `[ <geometry-box> | no-clip ]#` respectively, where `<geometry-box>` is defined:

```
<geometry-box> = <shape-box> | fill-box | stroke-box | view-box
<shape-box> = <box> | margin-box
```

The descriptions of how margin-box affects these two properties were removed, but the grammar would still indicate them to be valid.  Is there further editorial clarification to be made here?

**Comment by FormularSumo** [comment]
Bumping this, as I came across it in in https://github.com/web-platform-tests/wpt/pull/41279, https://github.com/mdn/content/pull/28157, https://github.com/mdn/browser-compat-data/pull/20461 and https://github.com/mdn/data/issues/678. According to https://github.com/w3c/fxtf-drafts/issues/5 and more recent testing browsers don't support margin-box on mask-origin and mask-clip, despite it still being a property of `<geometry-box>`, and don't plan to (especially given their support for its removal from wpts)

I suggest changing `<geometry-box>` to `<coord-box>`, which has the correct properties 
> `content-box | padding-box | border-box | fill-box | stroke-box | view-box`

offset-path changed from using <geometry-box> to <coord-box> between the [2018 working draft](https://www.w3.org/TR/motion-1/#offset-path-property) and the [2021 editor's draft](https://drafts.fxtf.org/motion-1/#offset-path-property) ([relevent commit](https://github.com/w3c/fxtf-drafts/commit/b0cc95afd8c874aaddb15e99339bd7c7d47ffea3)), presumably for similar reasons, which gave me the idea of doing it for mask-origin and mask-clip as well.

**Comment by progers** [comment]
Because the spec grammar still lists `margin-box` as valid for `mask-clip`, I implemented this in Chromium. I now see that this was wasted work because the spec intends that to be removed. Can we please accept @FormularSumo's pull request?

**Comment by dbaron** [comment]
The original issue for this was #5.
