### ISSUE TITLE
[css-motion] description of offset-position should be clearer

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#45]
My understanding of the [description of offset-position](https://drafts.fxtf.org/motion-1/#offset-position-property) is that the <code>auto</code> value is like relative positioning and the <code>&lt;position></code> value is like absolute positioning.

The description of this in the spec should actually make this clear.

**Comment by jihyerish** [comment]
You're right. `offset-position: < position>` is an absolute-positioning coordinate system.

For `offset-position: auto`, I think it could be more than relative positioning. 
We discussed about the result of `offset-position: auto` on [the previous telecon](https://lists.w3.org/Archives/Public/www-style/2016Jun/0158.html), and it was concluded to the current position of the element.
It means that when the element is absolutely positioned, specifying `offset-position: auto` to the same element doesn't change its positioning system.

In fact, we need more discussion about interaction between `offset-position` and the positioning system in https://github.com/w3c/fxtf-drafts/issues/77.

**Comment by ewilligers** [comment]
I suspect the best way to thing of the motion path properties is that they create a transform from where the element would be, without any of the motion path or transform properties, to the position that the motion path properties specify.

> +If 'position' is specified with 'static', 'offset-position' would be ignored.

Why? 'static' is the initial value for position, and the spec has numerous examples offset-position is set and position is not. Should they all be updated to explicitly set position? What is the benefit?
