### ISSUE TITLE
[compositing-2] syntax error in example 12 ?

### ISSUE THREAD

**Issue by letochagone** [w3c/fxtf-drafts#456]
I don't understand the syntax of example 12:
background-color: rgb(100% 0 0 / 50%);
what does this "/" mean? and why no comma between the members?

**Comment by faceless2** [comment]
See https://www.w3.org/TR/css-color-4/ for the syntax

**Comment by letochagone** [comment]
the syntax error is the zero <<rgb(100% 0 0 / 50%)>> the % is missing, without the % this example does not work under firefox.

**Comment by letochagone** [comment]
> See https://www.w3.org/TR/css-color-4/#rgb-functions for the syntax

the syntax error is the zero <<rgb(100% 0 0 / 50%)>> the % is missing, without the % this example does not work under firefox.

**Comment by SebastianZ** [comment]
@letochagone is right. The syntax in the example and other places in the spec. was wrong. CSS Color 4 only allows either all color components to be `<number>`s or `<percentage>`s, though not to mix them. So the `0` values must be expressed as `0%`. I've fixed that now in #457.

Sebastian

**Comment by SebastianZ** [comment]
I've now also [created an issue](https://github.com/w3c/csswg-drafts/issues/7338) to discuss whether combining `0` values with percentages should be allowed.

Sebastian
