### ISSUE TITLE
[compositing-2] Syntax for `background-blend-mode` denotes `mix-blend-mode` as a type instead of a property.

### ISSUE THREAD

**Issue by pyoor** [w3c/fxtf-drafts#463]
Properties must be defined as `<'name'>`.  The `background-blend-mode` syntax is rendered as: `<mix-blend-mode>#` where `mix-blend-mode` is a property.  I'm not exactly sure what's wrong with the source that would cause it to be rendered without the surrounding quotes.

https://github.com/w3c/fxtf-drafts/blob/3ee6470f08060bd235b51120648cc5b989db9cdd/compositing-2/Overview.bs#L293

**Comment by tabatkins** [comment]
It's just invalid Bikeshed right now - it needs to be `<<'mix-blend-mode'>>`.

**Comment by tabatkins** [comment]
fixed in 8f3a950
