### ISSUE TITLE
[motion-1] <path> is now one of the <basic-shape>

### ISSUE THREAD

**Issue by danielsakhapov** [w3c/fxtf-drafts#493]
The spec should be updated as <[path](https://drafts.fxtf.org/motion/#funcdef-offsetpath-pathfunc-path)> is now one of the <[basic-shape](https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-path)>.

**Comment by tabatkins** [comment]
Indeed.

**Comment by cdoublev** [comment]
I would expect some precision on `<'fill-rule'>` in [`path( [<'fill-rule'>,]? <string> )`](https://drafts.csswg.org/css-shapes-1/#funcdef-basic-shape-path), which I assume should be ignored. For example:

```diff
  <path()>
    The initial position is defined by the first “move to” argument in the path string. 
    For the initial direction follow SVG 1.1
+
+   The <fill-rule> argument is ignored.
```

Also reported in https://github.com/w3c/csswg-drafts/issues/7390
