### ISSUE TITLE
[motion-1] Explicit reference box for basic shapes

### ISSUE THREAD

**Issue by danielsakhapov** [w3c/fxtf-drafts#498]
For basic shapes it says [here](https://drafts.fxtf.org/motion/#offset-path-property) that 

> The [coord-box](https://drafts.csswg.org/css-box-4/#typedef-coord-box) specified in combination with a [basic-shape](https://drafts.csswg.org/css-shapes-1/#typedef-basic-shape) provides the reference box for the basic-shape. If no reference box is specified, it defaults to border-box.

But it's not clear that the reference box is the containing block (which I think it should be and has been agreed on [here](https://github.com/w3c/fxtf-drafts/issues/369)). Maybe make it more explicit to be so?

Event the [wpt test](https://wpt.fyi/results/css/motion/offset-path-shape.html) assumes it's the box itself.

**Comment by BorisChiou** [comment]
Yes. We should explicitly spec the reference box we would like to use. Hope we could fix this together with #369.

**Comment by tabatkins** [comment]
Explicit now. (See <https://github.com/w3c/fxtf-drafts/issues/369#issuecomment-1457239856> for details.)
