### ISSUE TITLE
[css-masking] mask-origin and mask-clip should not have a margin-box value

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#5]
[mask-clip](https://drafts.fxtf.org/css-masking-1/#the-mask-clip) and [mask-origin](https://drafts.fxtf.org/css-masking-1/#the-mask-origin) in [CSS Masking](https://drafts.fxtf.org/css-masking-1/) should not have a margin-box value.  The background-origin and background-clip properties that these are modeled after do not have a margin-box value, and neither Chromium nor WebKit implements such a value based on [my testcase](https://bug1260094.bmoattachments.org/attachment.cgi?id=8746863) .  Based on that, we decided [not to implement them in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1260094).

If there's a good reason for these values to exist, then:
- the spec should have a note pointing out that it is different from [background-origin](https://drafts.csswg.org/css-backgrounds/#the-background-origin) and [background-clip](https://drafts.csswg.org/css-backgrounds/#the-background-clip), and saying why
- the spec should explain what the margin box means in the presence of margin collapsing (possibly by linking to an appropriate definition)

**Comment by dirkschulze** [comment]
@dbaron Those values were added based on user feedback. I need to find the email correspondence to answer the question about relevance. IIRC it was added after a F2F meeting discussion.

**Comment by AstleyChen** [comment]
@dirkschulze could you help to provide more info here?
We need to clarify why do we need to support this value on mask-clip and mask-origin properties.

**Comment by dirkschulze** [comment]
@dbaron @astleychen Without `margin-box` any painting that exceeds the border box is going to get clipped away. As an example: box shadows and drop shadows disappear.

Apply `box-shadow: green 10px 10px 10px` to any element in the test case. It does not appear on any of the elements.

**Comment by mstange** [comment]
Isn't `mask-clip: no-clip` a better solution for that use case? Especially with `box-shadow` it's tricky to find the right margin that would contain the entire shadow; and you'd be affecting the geometry of the masked element by setting such a margin.

**Comment by dirkschulze** [comment]
@mstange you are right, in this case `no-clip` would be the better solution. On a quick search I couldn't find the discussion that lead to adding `margin-box`. Given that there is interop between 3 browsers (Blink and WebKit both do _not_ support `margin-box`) I'll remove the keyword on both properties unless there comes up a reasonable use case.
