### ISSUE TITLE
[filter-effects-1] Add edgemode=reflect

### ISSUE THREAD

**Issue by flackr** [w3c/fxtf-drafts#527]
A reflect edgemode in [filter-effects-1](https://drafts.fxtf.org/filter-effects-1/#element-attrdef-feconvolvematrix-edgemode) would be very useful as the behavior for the backdrop-filter blur behavior (See #374) as it avoids a discontinuity when moving the filter over new content.

The behavior of this mode would be that pixels outside mirror the pixels inside, e.g. it would be as follows:
Original N-by-M image, where m=M-1 and n=N-1:
```
 11  12 ...  1m  1M
 21  22 ...  2m  2M
... ... ... ... ...
 n1  n2 ...  nm  nM
 N1  N2 ...  Nm  NM
```

Extended by two pixels in each direction using reflect:
```
 22  21  21  22 ...  2m  2M  2M  2m
 12  11  11  12 ...  1m  1M  1M  1m
 12  11  11  12 ...  1m  1M  1M  1m
 22  21  21  22 ...  2m  2M  2M  2m
... ... ... ... ... ... ... ... ...
 n2  n1  n1  n2 ...  nm  nM  nM  nm
 N2  N1  N1  N2 ...  Nm  NM  NM  Nm
 N2  N1  N1  N2 ...  Nm  NM  NM  Nm
 n2  n1  n1  n2 ...  nm  nM  nM  nm
```

We can debate whether the border pixels should repeat in reflect mode, but doing so has the nice property that a 2N by 2M sampling is exactly one additional copy of the image worth of pixels.

**Comment by mstange** [comment]
Thanks for filing! For the current Firefox implementation it would be convenient if the reflection worked the same as in [`D2D1_BORDER_EDGE_MODE_MIRROR`](https://learn.microsoft.com/en-us/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_border_edge_mode), though we're going to move away from the D2D implementation eventually.

**Comment by tabatkins** [comment]
I don't know anything about the impl concerns of this, but is there a particular reason we're reflecting solely on the right/bottom edges? Or was this just an artifact of a simplified example, and a "real" reflect would also have reflected pixels along the top/left edges?

**Comment by flackr** [comment]
> Thanks for filing! For some parts of the current Firefox implementation (specifically Canvas2D filters on Windows) it would be convenient if the reflection worked the same as in [`D2D1_BORDER_EDGE_MODE_MIRROR`](https://learn.microsoft.com/en-us/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_border_edge_mode).

I'm not sure where it is defined, but looking at https://learn.microsoft.com/en-us/windows/win32/direct2d/border#mirror it does look like the mirroring is equivalent to the proposal here - repeating the border pixels - such that you can draw an image 2x the original size and have exactly one mirrored copy.
