### ISSUE TITLE
[css-masking-1] Remove margin-box from description mask-clip

### ISSUE THREAD

**Issue by alkorlos** [w3c/fxtf-drafts#534]
In the specification [CSS Masking Module Level 1](https://drafts.fxtf.org/css-masking-1/) in the section [Changes since last publication](https://drafts.fxtf.org/css-masking-1/#changes) in the list “The following changes were made since the [26 August 2014 Candidate Recommendation](https://www.w3.org/TR/2014/CR-css-masking-1-20140826/).” has change:

> Remove margin-box as possible value from [mask-origin](https://drafts.fxtf.org/css-masking-1/#propdef-mask-origin) and [mask-clip](https://drafts.fxtf.org/css-masking-1/#propdef-mask-clip).

Value `margin-box` removed from `mask-clip`, but in the [7.5. Masking Area: the mask-clip property](https://drafts.fxtf.org/css-masking-1/#the-mask-clip) value `margin-box` left in description:

> For SVG elements without associated CSS layout box, the [used value](https://drafts.csswg.org/css-cascade-5/#used-value)s for [content-box](https://drafts.fxtf.org/css-masking-1/#valdef-mask-clip-content-box) and [padding-box](https://drafts.fxtf.org/css-masking-1/#valdef-mask-clip-padding-box) compute to [fill-box](https://drafts.fxtf.org/css-masking-1/#valdef-mask-clip-fill-box) and for [border-box](https://drafts.fxtf.org/css-masking-1/#valdef-mask-clip-border-box) and margin-box compute to [stroke-box](https://drafts.fxtf.org/css-masking-1/#valdef-mask-clip-stroke-box).

**Comment by FormularSumo** [comment]
This looks to be along the same lines as https://github.com/w3c/fxtf-drafts/issues/439, and likewise looks like it was just forgotten about. Also seems to be the only outdated use of margin-box that remains in the sepc - hopefully your PR will get merged soon! Pinging @dbaron who merged my related PR.

**Comment by alkorlos** [comment]
When I read this spec first I saw `mask-clip` and `mask-origin` have grammar `<geometry-box>`, however they have no value `margin-box`, found https://github.com/w3c/fxtf-drafts/issues/439, this was a known issue, it was fixed a couple of days after the current issue was created.

Later I saw `margin-box` in description `mask-clip`, similar error, but in a different place.

Thank you for pinging!
