### ISSUE TITLE
[motion] Merge 'offset-rotate' and 'offset-anchor' with CSS Transforms Module

### ISSUE THREAD

**Issue by SebastianZ** [w3c/fxtf-drafts#54]
As [`offset-rotation`](https://drafts.fxtf.org/motion-1/#offset-rotation-property) and [`offset-anchor`](https://drafts.fxtf.org/motion-1/#offset-anchor-property) are related to transformations, those two properties might rather be merged with the CSS Transforms Module.

I.e. the [`rotate()`](https://drafts.csswg.org/css-transforms/#funcdef-transform-rotate) function of the 'transform' property could be extended so that it also takes the keywords of `offset-rotate`, and [`transform-origin`](https://drafts.csswg.org/css-transforms/#transform-origin-property) would be used instead of having the separate property `offset-anchor`.

So the syntax for `rotate()` would then look like this:

    rotate( [ auto | reverse ] || <angle> )

Multiple transform functions would still be accumulated like now, meaning, in a value of `rotate(reverse) rotate(reverse)` the two `rotate()` functions would neutralize each other.

*For reference, this was initially [mentioned by me in a www-style thread](https://lists.w3.org/Archives/Public/www-style/2016Oct/0071.html).*

Sebastian

**Comment by shans** [comment]
We deliberately chose to have a separate offset-anchor because it needs to be different to transform-origin in some cases.

We've talked about merging offset-rotation with transforms before, but it doesn't really make sense because in the general case rotate(auto) doesn't give you the effect that you want:

(1) it would be dependent on any previous transform functions
(2) it would rotate about the transform-origin which as described is not always the same as offset-anchor.

I also think the accumulation behavior you describe is confusing and hard to reason about. For example two rotate(reverse) functions would not neutralize each other, but would instead cause the element to rotate by twice the angle between horizontal and the tangent to the curve. All of this is caveat the rotations being at the beginning of the transform list and actually next to each other - if you don't do that then things get even harder to work out.

I'm going to close this issue as we did discuss during WG F2F meetings in May and decided against this approach.

**Comment by SebastianZ** [comment]
> I'm going to close this issue as we did discuss during WG F2F meetings in May and decided against this approach.

I couldn't [find minutes about this on www-style](https://lists.w3.org/Archives/Public/www-style/2016May/thread.html). Is there a discussion protocol somewhere?

> We deliberately chose to have a separate offset-anchor because it needs to be different to transform-origin in some cases.
> 
> We've talked about merging offset-rotation with transforms before, but it doesn't really make sense because in the general case rotate(auto) doesn't give you the effect that you want:
> 
> (1) it would be dependent on any previous transform functions
> (2) it would rotate about the transform-origin which as described is not always the same as offset-anchor.

Could you provide examples for both where this is causing an unexpected result?

I'd define to let `rotate(auto)` only have an effect when an offset path is defined, in other cases it would behave like `rotate(0deg)` was defined. `rotate(reverse)` would behave like `rotate(180deg)`, accordingly.

> I also think the accumulation behavior you describe is confusing and hard to reason about. For example two rotate(reverse) functions would not neutralize each other, but would instead cause the element to rotate by twice the angle between horizontal and the tangent to the curve. All of this is caveat the rotations being at the beginning of the transform list and actually next to each other - if you don't do that then things get even harder to work out.

I assume web authors would rather expect two `rotate(reverse)` functions to result in a 360 degrees rotation than rotating twice by the angle between horizontal and tangent of the curve, but you're right, the current accumulation rules would result in the same angle being applied twice.

Sebastian

**Comment by shans** [comment]
> I couldn't find minutes about this on www-style. Is there a discussion protocol somewhere?

I believe much of the discussion was informal, however there's a later thread here that continues the discussion: https://lists.w3.org/Archives/Public/www-style/2016Jun/0077.html.

> Could you provide examples for both where this is causing an unexpected result?

(1) `scale(-1, 1) rotate(auto)` or `rotate(auto) scale(-1, 1)` (possibly both) are simple examples that behave strangely in the presence of a motion path.
(2) any time you want a different transform origin and path origin. For example, if you scale a model of a plane you'll want to scale it around the center (so it grows evenly in all dimensions) but you probably want the path-following point to be between the wings.

> I assume web authors would rather expect two rotate(reverse) functions to result in a 360 degrees rotation than rotating twice by the angle between horizontal and tangent of the curve

This is exactly the problem. Author expectation is not going to match mathematical outcomes in all cases but the super simple ones. That causes a lot of author surprise, which I think is a hallmark of bad API design.

**Comment by jihyerish** [comment]
> I couldn't find minutes about this on www-style. Is there a discussion protocol somewhere?

You can also see the discussion on here [1] . 
This discussion ended up :
- `offset-rotation` is independent of transforms during the cascade
- `offset-rotation` is applied before the transforms

[1] http://w3-org.9356.n7.nabble.com/round-display-motion-path-Orientation-of-elements-due-to-merging-polar-positioning-and-motion-path-td319694.html

**Comment by SebastianZ** [comment]
> Could you provide examples for both where this is causing an unexpected result?
> 
> (1) scale(-1, 1) rotate(auto) or rotate(auto) scale(-1, 1) (possibly both) are simple examples that behave strangely in the presence of a motion path.

I see. Well, one could argue for or against this being unexpected. And in which order transformations are applied may be unexpected independently from the presence of a motion path.

> (2) any time you want a different transform origin and path origin. For example, if you scale a model of a plane you'll want to scale it around the center (so it grows evenly in all dimensions) but you probably want the path-following point to be between the wings.

Ah, right. I missed that `transform-origin` does not take a list like other properties. I saw there was [some discussion about this](https://lists.w3.org/Archives/Public/www-style/2012Feb/0201.html) previously. I picked that up again in https://github.com/w3c/csswg-drafts/issues/589.

>> I couldn't find minutes about this on www-style. Is there a discussion protocol somewhere?
> 
> You can also see the discussion on here [1] .
> This discussion ended up :
> 
>     `offset-rotation` is independent of transforms during the cascade
>     `offset-rotation` is applied before the transforms

Thank you for pointing me at that, Jihye! When it's applied before the transforms, we'll still run into the issues mentioned by @shans, though. As of my understanding, it should be applied **afterwards** then.

I still need to read through that thread, but so far I still believe transforms should be reused for this use case.

Sebastian
Sebastian
