### ISSUE TITLE
[geometry] Usage of 'none' in DOMMatrix transform lists

### ISSUE THREAD

**Issue by tim-loh** [w3c/fxtf-drafts#55]
The DOMMatrixReadOnly(transformList)/DOMMatrix(transformList) constructors and setMatrixValue(transformList) functions all parse transform lists. Is the 'none' keyword supposed to be supported by these?

The spec prose says to parse to a &lt;transform-list&gt;, but the 'none' keyword is not a valid &lt;transform-list&gt;, but it seems to suggest that it should be supported as it explicitly says to reject any other keywords. The subsequent portions of the procedures also don't support the 'none' keyword.

**Comment by zcorpan** [comment]
Thank you! Please let me know what name you prefer for the spec's Acknowledgements. 😊

**Comment by tim-loh** [comment]
Thanks for the spec fix! I think setMatrixValue(transformList) needs to be
updated too.

For the spec Acknowledgements, "Timothy Loh" would be fine.

**Comment by zcorpan** [comment]
> Thanks for the spec fix! I think setMatrixValue(transformList) needs to be
updated too.

Fixed in https://github.com/w3c/fxtf-drafts/commit/fe7fe4e17c68b450cd487753b762a3d0b3f1a9cc

> For the spec Acknowledgements, "Timothy Loh" would be fine.

Added in https://github.com/w3c/fxtf-drafts/commit/f842b603a8800b191749fd96cdc544efc13df306

Thanks again!
