### ISSUE TITLE
[css-masking] some sites expect mask-repeat initial value to be 'repeat'

### ISSUE THREAD

**Issue by RByers** [w3c/fxtf-drafts#56]
Blink tried to change it's default value for `-webkit-mask-repeat` from `repeat` to `no-repeat` to match [the mask-repeat spec](https://drafts.fxtf.org/css-masking-1/#propdef-mask-repeat), but that got reverted for [breaking](https://bugs.chromium.org/p/chromium/issues/detail?id=645000) some prominent websites including twitter.com.  Apparently Firefox has seen some similar issues as well.

Worth considering changing the spec here?

Note that I don't work in this space, just transferring information from [a chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=628968) to where (IMHO) it belongs - an issue for the WG.  Please follow up with @tabatkins and members of the blink style team (/cc @shans since I don't know the right GitHub accounts).

**Comment by mstange** [comment]
see also https://github.com/w3c/csswg-drafts/issues/599

**Comment by RByers** [comment]
Oh sorry - this is a dupe then - I somehow missed that bug in my search.

**Comment by mstange** [comment]
This repository might be a more appropriate place for the issue, though. I'm not sure.
