### ISSUE TITLE
[motion-1] description of interactions should be a little bit more formal

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#57]
The [description of module interactions](https://drafts.fxtf.org/motion-1/#placement) explaining how motion-path interacts with transform (and rotate, scale, etc.) should probably be a little bit more formal than the current prose, which is:

> Some CSS properties in this specification manipulate the user coordinate system of the element by transformations. These transformations are pre-multiplied to transformations specified by the transform property or deriving properties.

It should probably at least cite the other specification that it hooks into and say more specifically where it hooks in.

I got here from https://github.com/w3ctag/spec-reviews/issues/66

**Comment by dbaron** [comment]
It also should specify explicitly that having these properties causes the elements to do all the other things that being transformed does, e.g., creating stacking context, in a formal way that hooks into transforms.

**Comment by ewilligers** [comment]
> It should probably at least cite the other specification that it hooks into and say more specifically where it hooks in.

We should cite https://drafts.csswg.org/css-transforms-2/#ctm

**Comment by jihyerish** [comment]
I modified the module interaction like:

> This specification defines a set of CSS properties that affect the visual rendering of elements to which those properties are applied. These effects are applied after boxes have been sized and positioned according to the Visual formatting model from [CSS21]. Some values of offset-path and offset-position result in the creation of a stacking context and containing block.
> Some CSS properties in this specification manipulate the user coordinate system of the element by transformations. These transformations are pre-multiplied to transformations specified by the transform property or deriving properties defined in CSS Transform Module Level 1 [CSS-TRANSFORMS-1].

@dbaron @ericwilligers  Is it okay to close this issue?
