### ISSUE TITLE
[motion-1] examples could be clearer

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#59]

**Comment by dbaron** [comment]
Some of the examples in motion-path, e.g., https://drafts.fxtf.org/motion-1/#offset-path-property , could be substantially clearer if they included more (or all) of the code needed to produce the result shown.

For example, in https://drafts.fxtf.org/motion-1/#offset-path-property , one div is red and the other is blue; specifying 'background: red' and 'background: blue' in the code snippet would make it clearer what's happening.

I think similar things apply to other examples in the spec.

I got here from https://github.com/w3ctag/spec-reviews/issues/66

**Comment by jihyerish** [comment]
Thanks for the review : )
I modified examples and you can see the change here :  https://github.com/w3c/fxtf-drafts/commit/0972beca23ae9cb488e85e67b87ee62c82e5a11b
