### ISSUE TITLE
[motion] contain should modify percentages, not path

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#61]
> contain
>   When the absolute value of offset-distance would select a point on the path which is outside the edge of the containing element, the value is instead clipped so that the selected point lies on the edge of the element. 

The `contain` value would make a lot more sense if, instead of clipping the `offset-distance`, it merely altered the interpretation of percentages so that 100% placed the element wholly inside its containing block. IIRC this was the original reason for placing it as part of the `offset-path` property rather than `offset-distance`: it operates by altering the length of the path, not by altering the distance along it. This will make percentages interpolate much more reasonably than the currently specified model.

**Comment by ewilligers** [comment]
The spec currently has
"Defining a path with \<angle\>, the element can be positioned with the used of polar coordinates. "

The suggestions in #61 and #73 would each prevent polar positioning: the distance that a given percentage translates to would depend on the direction.

Here is a server-side implementation of CSS Motion Path for rays, based on my understanding of the current spec:  https://goo.gl/32E9Vq
Example without contain: https://goo.gl/1IpMxH
Example with contain: https://goo.gl/sE0yvA

The examples use
`offset: ray(45deg) 100% 0deg OR ray(45deg contain) 100% 0deg`
`offset: ray(180deg) 100% 0deg OR ray(180deg contain) 100% 0deg`
`offset: ray(120deg) -120% 0deg OR ray(120deg contain) -120% 0deg`

The clamping for 'contain' happens at the last possible moment, and takes into account the offset-rotation and the offset-anchor. Whenever offset-distance is sufficiently small, 'contain' has no effect on the interpretation of percentages, and we achieve polar coordinates.

**Comment by jihyerish** [comment]
I agree with fantasai's opinion. 
I added a description on the spec that `contain` adjusts the total length of the path not the value of `offset-distance`.
