### ISSUE TITLE
[motion] none value considerations

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#64]
1. > For <angle>, the initial value none is interpreted as 0deg, the element can be positioned along the y axis.

    Seems like this sentence shouldn't exist? I can't figure out what it means, anyway.

2. > `none` No path gets created.

    What does `offset-distance` mean in the presence of `offset-path: none`? If the element doesn't move, then maybe say so, e.g. "and `offset-distance` has no effect".

3. What happens with `offset-rotation` in this case? Is the path assumed be `0deg` or is `offset-rotation` ignored?

**Comment by ewilligers** [comment]
I agree that offset-distance has no effect if offset-path is none (or an unresolved url).

With regards to offset-rotation:
Option A
No rotation occurs unless offset-position and/or offset-path are set.
If offset-path is an unresolved url, or offset-position is set and offset-path is none, rotation 'auto' is equivalent to '0deg' - i.e. the path has an assumed bearing of 90deg.

Option B
If we would like rotation to occur with offset-position 'auto' and offset-path 'none', the spec needs to mention that rotation other than 'auto' creates a stacking context.

**Comment by ewilligers** [comment]
I believe this issue can now be closed.

The sentence from point 1 is no longer in the spec.

Points 2 and 3 are addressed by
https://drafts.fxtf.org/motion-1/#valdef-offset-path-none

> When offset-path is none, offset-distance and offset-rotate have no effect.
