### ISSUE TITLE
[motion] offset-rotation should only do path-relative rotation

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#69]
Currently `offset-rotation` can specify an arbitrary rotation as well as a path-relative rotation. Afaict, this duplicates functionality in the `rotate` property, and therefore isn't really necessary.

The current syntax is
```
offset-rotation: [ auto | reverse] || <angle>
```

I propose
```
offset-rotation: none | forwards | backwards | <angle>
```
Where `forwards` computes to `0deg`, `backwards` computes to `180deg`, and any value other than `none` tracks the path tangent.  (The choice of `forwards` and `backwards` keywords is to match the pair in `animation-fill-mode`.)

Alternatively, the <angle> value could also be dropped in favor of further tweaking with `rotate`.

**Comment by jihyerish** [comment]
I didn't know there is `rotate` property before, thanks for letting me know.
The < angle > value part of `offset-rotation` is obviously the same with that of `rotate`.

I'm in favor of dropping < angle > from the offset-rotation, so the syntax will be: 

> `offset-rotation: none | forwards | backwards`

**Comment by shans** [comment]
offset-rotation can't be used in place of rotate, and (to a degree) vice versa. Depending on the order of offset and translate/rotate/scale - if rotate happens after offset then these two are different:
```
offset: path("...") auto 45deg;
translate: 100px;
```
and

```
offset: path( ... ) auto;
translate: 100px;
rotate: 45deg
```

Alternatively, if rotate happens before offset then these two are:

```
offset: path("...") 45deg;
```

and 

```
offset: path("...");
rotate: 45deg;
```

**Comment by shans** [comment]
I also want to strongly make the point that you keep talking about adjusting a specification that we have already shipped. We'd love to accommodate reasonable changes where we can (e.g. we've done this for the motion-* to offset-* rename, and are currently trying to determine if offset-rotation can be renamed to offset-rotate), but the larger the change and the later it's suggested the less likely we're going to be able to comply.

In practice the risk is that we have to support multiple variants of the feature (or just not support the new syntax at all, if it is dissimilar enough that we can't support both). This will potentially cause web compat problems.
