### ISSUE TITLE
[motion][naming] offset-rotation vs rotate

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#70]
We have a `rotate` property in css-transforms-2 and an `offset-rotation` property in motion-1. They should be grammatically consistent. Propose to rename `offset-rotation` to `offset-rotate`, unless people have a strong argument for going the other way.

**Comment by jihyerish** [comment]
I will request to add this topic as an agenda item for Conf call next week.

**Comment by atanassov** [comment]
CSSWG: Resolution: rename the offset-rotation property to offset-rotate in favor of consistency with the rotate property and values of transforms.
Additional action to the Blink team to figure out if this is something they can rename.

**Comment by jihyerish** [comment]
@ericwilligers On the last CSSWG Telecon, this issue resolved to rename `offset-rotation` to `offset-rotate`.
Will renaming matter for the implementation on Blink?

**Comment by yisibl** [comment]
offset-rotate +1

**Comment by ewilligers** [comment]
Was there any discussion or decision regarding #69 ?

Also, can #51 be closed?

**Comment by jihyerish** [comment]
The issue #69 is still under discussion. There isn't a clear resolution yet.

**Comment by ewilligers** [comment]
blink-dev proposal for shipping offset-rotate in Blink: https://groups.google.com/a/chromium.org/d/msg/blink-dev/o1C5NzGf9Q0/FgU5o52yBAAJ

**Comment by ewilligers** [comment]
offset-rotate has now shipped in Chrome 56.
