### ISSUE TITLE
[motion] Airplane rotation example should show unrotated airplane

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#71]
The effect of `offset-rotation` would be clearer if the examples started by showing the unrotated airplane (before any `offset-*` properties are applied).

**Comment by jihyerish** [comment]
> (before any offset-* properties are applied)

Do you mean before both `offset-path` and `offset-rotation` are applied?
I think that `offset-rotation` has dependency on `offset-path`, so I think `offset-rotation` will work only if `offset-path` is specified.
If the `offset-path` is specified, than the element's rotation is decided by initial direction which is defined for the each path case.

**Comment by ewilligers** [comment]
I have added Option C to my comment in https://github.com/w3c/fxtf-drafts/issues/64 for the suggestion that offset-rotate only has effect when offset-path is specified.
