### ISSUE TITLE
[motion] Should omitted <size> just extend to the containing block edge?

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#73]
> <size>
>    Decides the position of the end point of the path. ...  If omitted it defaults to closest-side.

I think it's quite reasonable that someone might want to position along a polar ray between the initial point and the edge of the containing block at a non-orthogonal angle. Simplest way to allow this would be that if an omitted size argument were left out, the ray extends to the edge of the containing block at the specified angle. Constraining `100%` to match regardless of `<angle>`  would require a keyword, but I don't think this is unreasonable. In particular it'd be less surprising in cases where the initial position chosen as one of the corners (or along an edge), which is a fairly common and reasonable case, but would result in a (surprising) path distance of zero.

**Comment by jihyerish** [comment]
> someone might want to position along a polar ray between the initial point and the edge of the containing block at a non-orthogonal angle.

Previously, Motion Path Spec described that the end point of the path is the point where the ray with < angle > meets the edge of the containing block.
But this caused the inconsistency in `offset-path` when the < angle > is different but the percentage value of `offset-distance` is the same. 
So I thought the default value as `closet-side` can solve the inconsistency, it makes the calculated position of the element constant with the changes in < angle > of the path.

Specifying `furthest-corner` for < size > can position the element along a polar ray between the initial point and the edge of the containing block at a non-orthogonal angle.

It's hard for me to find the better option than `closet-side` for the default of < size >.

**Comment by jihyerish** [comment]
> In particular it'd be less surprising in cases where the initial position chosen as one of the corners (or along an edge), which is a fairly common and reasonable case, but would result in a (surprising) path distance of zero.
On that case, can we choose the closet side among the edges which don’t adjacent with the element?
