### ISSUE TITLE
[motion] Better definitions for initial position and initial direction

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#76]
> Each shape or path must define an initial position for the computed value of "0" for offset-distance and an initial direction which specifies the rotation of the object on the initial position.

There's two things wrong here: 
- "computed value of `0`" isn't the phrase you want to use here, because `0%` and `0` are not equivalent computed values, but they should be treated equivalently here
- the initial direction only specifies the rotation of the object on the initial position if `offset-rotation` is defined to follow the path direction

So you need to make a stronger and more correct definition of these terms.

(Also, while you're at it, split this into a new paragraph? It's not the core definition of the property, so shouldn't be in that first paragraph.)

**Comment by jihyerish** [comment]
Then how about the definitions like this:

> The initial position of the element when "0%" is given for `offset-distance` must be defined for each path defined by shape for svg < path >. Also the initial direction of the element positioned along the path describes the rotation of the element if `offset-rotation` is specified.

**Comment by jihyerish** [comment]
> he initial direction only specifies the rotation of the object on the initial position if offset-rotation is defined to follow the path direction

The initial position is the position of the element on the path before offset-position is specified and the initial distance is the rotation before offset-rotation is specified.
So I think the initial position is a default value of offset-distance and the offset-position is a default value of offset-rotation.

Am I understanding something wrong?

Therefore the initial position has the same result when offset-distance is 0%, and the initial direction is differ from the value type of offset-path.
