### ISSUE TITLE
[motion] Interaction with positioning

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#77]
Some of the earlier discussions on polar positioning discussed its interaction with regular CSS positioning. Some of the topics that came up were
  * Do the `left`, `right`, `top`, `bottom` properties have an effect?
  * Should polar positioning respond to `position: absolute` vs `position: relative` vs `position: static` vs `position: fixed`?

The first question was left open, and the second question was concluded as "definitely yes". Under that system, polar positioning was ignored under `static`, used the element's normal position as its origin (and took up space in its container) for `relative`, and took the element out of flow and used the polar origin for `absolute` and `fixed`.

The current spec merges this system with the motion transform proposal, and hence operates at a layer on top of CSS positioning. This means the interaction with `position` is handled as simply the differences in determining the "containing block" when laying out the path, with `static` and `relative` reserving space and `absolute` and `fixed` taking it out of flow. The interaction with `left`, `right`, `top`, `bottom` is through them determining the initial position when `offset-position` is `auto` and `position` is not `static`; they are otherwise ignored.

This seems pretty sane, but just wanted to check that everyone is on board with this. It does mean we have two absolute-positioning coordinate systems (`left`, `right`, `top`, `bottom` vs `offset-position: <position>`) that work through two different positioning systems.

On a related note, if `left`, `right`, `top`, `bottom` don't actually interact directly with the `offset-` properties, that means we should definitely rename their logical equivalents.  https://github.com/w3c/fxtf-drafts/issues/51 If we think they should have some interaction (e.g. reducing the size of the containing block, similar to the effect they have when applied to grids or the effect they have on the alignment properties), then they should have matching prefixes.

**Comment by jihyerish** [comment]
> This seems pretty sane, but just wanted to check that everyone is on board with this.

I agree with this.
We had quite a lot of discussion about the interaction between offset-position (prev. polar-origin) and positioning and we need to define how offset-position (something could be polar positioning) interacts with position: absolute or position: relative or position: fixed.

I think `offset-position` could be work as: 
- If `< position >` is given to offset-position, 
  - element is positioned as absolute positioning
  - `left`, `right`, `top`, `bottom `are ignored
- If `auto` is given to offset-position,
  - element is positioned as it was
eg) For a relatively positioned element, specifying offset-position: auto to the same element doesn't change its positioning system.

**Comment by ewilligers** [comment]
There are a couple of special cases where this isn't the full story.

If offset-position is a position, the motion path translation (and hence left/right/top/bottom if position is 'absolute') can be observed if 'rotate' or 'scale' are set.
https://drafts.csswg.org/css-transforms-2/#ctm

If offset-path is a geometry-box, or a basic shape (other than a circle or ellipse with implicit center), then the value of offset-position is ignored and we have absolute positioning even if offset-position is 'auto' and position is 'static'.
https://drafts.fxtf.org/motion-1/#offset-path-property

I have prepared a pull request to make this clearer, with these cases as examples.
