### ISSUE TITLE
[motion] No model for interaction of `offset-position` and shapes

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#78]
`<basic-shape>`s have their own position information. IIRC SVG shapes do, too. How does this interact with the `offset-position` property?

First, what are all our options here? (I think it's worth exploring since there hasn't been any discussion of it.) Second, which one should we choose and why?

**Comment by ewilligers** [comment]
I suspect offset-position (and the element's current position if offset-position is auto) should be ignored when offset-path is  `<basic-shape> || <geometry-box>`.

Authors may use shape-outside, clip-path and offset-path together, wanting all to refer to the same shape in the same location.

**Comment by AmeliaBR** [comment]
If  `offset-position` only applies to certain types of shapes (i.e., directional ray lines), it should be defined as part of the shape definition, not as a separate property.

The syntax for a ray could be `ray(<angle> && <size>? [at <position>]? && contain?)`.

For more general translations, a `translate` transform could be used. Although, I'm still not clear how `transform-origin` interacts with all of this.

**Comment by ewilligers** [comment]
Note that `offset-position` also applies when `offset-path` is path() or none.

**Comment by shans** [comment]
As a counter suggestion, what's wrong with offset-position applying as an offset to the shape's position? This avoids annoying discontinuities (neutral changes to shape don't cause jumps in location).

**Comment by ewilligers** [comment]
> As a counter suggestion, what's wrong with offset-position applying as an offset to the shape's position? This avoids annoying discontinuities (neutral changes to shape don't cause jumps in location).

Q1. Would offset-position also apply as an offset when offset-path is \<geometry-box\> ?

Q2. If we have
`position: absolute;
offset-position: auto;
offset-path: <geometry-box>;`
would left/top be relevant?

**Comment by shans** [comment]
We discussed this at length after the f2f. Essentially we realized that there's a matrix of desirable behaviors:

(1) the offset element can be positioned either relative to its container, or relative to its laid out position
(2) the path can be defined with units relative to the container, or with units relative to the element (note that SVG content is currently unable to provide relative units and so is a subset of both of these)

For paths and rays, offset-position: auto opts into element-relative positioning, while other offset-position values anchors the path inside the container (note that there is some discussion about exactly how this should work for paths, one mechanism is that paths implicit moveto is to (0,0) if none is specified, and that the coordinate space for a motion path is zeroed at the offset-position.)

We could allow the same behavior for basic shapes with a position (circles and ellipses) if we specified that omitting position information for these shapes falls back to the position specified in offset-position.

This is not true of other shapes or geometry boxes, however - they're always defined relative to the container and don't have a position.

In other words, we have:

|  | no relative coordinates | coords relative to container | coords relative to element |
|-|---------------------|----------|--------|
| position rel to container | path()*, url() | ray(), circle(), ellipse(), other shapes, boxes | |
| position rel to element | path()*, url() | ray(), circle()@, ellipse()@ | |

* assuming we can "start" paths at the offset-position
@ if circles and ellipses fallback on offset-positioning for position

Given that nothing operates relatively to elements yet, we think this can be deferred to L2. That leaves the following problems:
(1) paths can't be specified relative to the container. One suggestion for fixing this was to define a CSS path syntax.
(2) there's no simple rectangle or polygon shape that can be positioned relative to the element. CSS path syntax somewhat fixes this, but for rectangles we thought that adding a new rect() type that included a position and width/height information would be useful.
(3) we need to specify the fallback behavior for circle and ellipse
(4) we need to specify path() positioning and make sure it makes sense

@tabatkins @fantasai @jihyerish did I capture our discussion correctly?

**Comment by fantasai** [comment]
Overall seems about right. I'm strongly in favor of having the omitted <position> arguments default to `offset-position` as we discussed. Didn't quite follow what you meant with moveto 0,0 but I'll assume it's correct. :) Happy to leave the coords relative to element column to L2 or beyond, depending on user demand.
