### ISSUE TITLE
[motion] Use 'position: relative' instead of 'opacity: 0' for stacking context descriptions

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#79]
The `opacity` property is a bit weird in the way that it creates a stacking context on one value of a continuum. `position: relative` might be a better example to use here. Also IIRC `position: relative` doesn't have an effect on SVG elements, so it would match the "doesn't create a stacking context in SVG" behavior.

**Comment by ewilligers** [comment]
We also need to mention a containing block. We could copy the wording used by perspective:

https://drafts.csswg.org/css-transforms/#perspective-property
"The use of this property with any value other than none establishes a stacking context. It also establishes a containing block (somewhat similar to position: relative), just like the transform property does."

**Comment by fantasai** [comment]
@ewilligers That is a separate issue...
