### ISSUE TITLE
[css-masking] Example 15's illustration image is wrong

### ISSUE THREAD

**Issue by mstange** [w3c/fxtf-drafts#84]
https://drafts.fxtf.org/css-masking-1/#example-0d5257dd

The example wants to demonstrate `subtract(trapezoid, add(circle, rect))`, but the image looks like it shows `intersect(trapezoid, add(circle, rect))`. Either the `mask-composite` value in the example should be changed from `subtract` to `intersect`, or the image needs to be updated to show the trapezoid shape being cut out from the union of the rect and the circle, instead of the trapezoid being intersected with it.

**Comment by dirkschulze** [comment]
@mstange You are right. I added an issue to the spec for now and will update the figure.
