### ISSUE TITLE
Inconsistent rules for <title>, <desc> and <metadata>

### ISSUE THREAD

**Issue by jarek-foksa** [w3c/fxtf-drafts#9]
The spec allows descriptive elements (`title`, `desc` and `metadata`) as children of certain elements (`filter`, `feSpecularLighting`) while disallowing them on others (`feBlend`, `feColorMatrix`).

For the sake of consistency I would either allow or disallow them everywhere.

**Comment by jarek-foksa** [comment]
Actually, `title` and `desc` makes sense as a child of a `filter` (e.g. to provide a filter name to be displayed by authoring tools or a human-readable description of what the filter does), but I can't think of any situation where I would want to put in inside a filter primitive.

**Comment by Tavmjong** [comment]
At our weekly telecon: RESOLUTION: title and desc can be a child of any svg namespaced element except switch

**Comment by AmeliaBR** [comment]
I'll get the SVG 2 prose description of title & desc updated in the next couple weeks, along with the element metadata that defines allowed child content.  

If anyone wants to review the FXTF specs & figure out where changes would be required, that would be wonderful.  I'm assuming they've mostly borrowed the definitions.xml files from SVG, but haven't looked too closely.

**Comment by dirkschulze** [comment]
@Tavmjong @AmeliaBR Do you have a link to the resolution?

**Comment by AmeliaBR** [comment]
@dirkschulze 

The minutes are hardly up to CSSWG standards, but they're here: https://www.w3.org/2016/06/09-svg-minutes.html#resolution04

**Comment by dirkschulze** [comment]
@AmeliaBR This is a FX spec, a joint venture of the SVG WG and the CSS WG. This definitely is in the domain of SVG :)

**Comment by AmeliaBR** [comment]
@dirkschulze I didn't mean to suggest that SVG WG resolutions were any less valid, only that the minutes were rather sparse and un-edited, so there isn't a lot of detail about the discussion that led up to the resolution.
