### ISSUE TITLE
[css-masking-1] [filters] Remove "* implements SVGUnitTypes"

### ISSUE THREAD

**Issue by foolip** [w3c/fxtf-drafts#90]
See https://github.com/w3c/svgwg/issues/291#issuecomment-254930687. (Editing this repo looks less trivial than most specs, so no PR.)

**Comment by foolip** [comment]
The interfaces are SVGClipPathElement, SVGMaskElement and SVGFilterElement.

**Comment by foolip** [comment]
@nikosandronikos, do you know who to poke about these specs?

**Comment by nikosandronikos** [comment]
I built this using `make`, with no additional arguments. There's a ton of changes in the built spec. As far as I can tell they're benign, but is this expected?

**Comment by foolip** [comment]
There's also SVGClipPathElement and SVGMaskElement. Who has the power to reopen?

**Comment by dirkschulze** [comment]
I'll do the edits.

**Comment by dirkschulze** [comment]
Done. Please review and reopen if I missed something.
