### ISSUE TITLE
[css-transforms-1] Call out scrolling offsets explicitly in accumulated matrix computation

### ISSUE THREAD

**Issue by surma** [w3c/fxtf-drafts#98]
In [Section 6.1.4](https://drafts.csswg.org/css-transforms/#accumulated-3d-transformation-matrix-computation) it _seems_ to me that scrolling offsets are applied in step 4.2. If that is the case, is it worth calling that out explicitly?

**Comment by fantasai** [comment]
Hi Surma, could you refile this in the CSSWG repo please? Thanks :)

**Comment by surma** [comment]
Done! :)
