### ISSUE TITLE
[css-masking] Add mask-repeat-x/y

### ISSUE THREAD

**Issue by kuoe0** [w3c/fxtf-drafts#99]
Latest spec: [https://www.w3.org/TR/css-masking/#the-mask-repeat](https://www.w3.org/TR/css-masking/#the-mask-repeat)

In this [discussion](http://lists.w3.org/Archives/Public/www-style/2014Apr/0188.html), `background-repeat-{x|y}` will be added to **background-4**. There is also already a spec [issue](https://github.com/w3c/csswg-drafts/issues/116) on csswg-drafts.

As the counterpart of background, it also makes sense to add `mask-repeat-{x|y}` to the spec.

**Comment by KuoE0** [comment]
@birtles How do you think for this?

**Comment by svgeesus** [comment]
Probably, but note the warning issue in the css backgrounds 4 spec:

>  This section is still being worked out. The tricky thing is making all the start/end keywords work sanely.

https://drafts.csswg.org/css-backgrounds-4/#background-position-longhands

**Comment by dbaron** [comment]
I wrote [some tests](https://dbaron.org/css/test/2017/mask-repeat-x-y) to see if any implementations support these.

**Comment by dbaron** [comment]
We discussed these at the Seattle face-to-face as described in https://github.com/w3c/csswg-drafts/issues/116#issuecomment-273887240

**Comment by astleychen** [comment]
Which suggested mask-repeat-{x|y} won't be speced too ? If it's the case, what's the resolution of this bug ?

**Comment by dirkschulze** [comment]
Based on https://github.com/w3c/csswg-drafts/issues/116#issuecomment-275179463 those properties should not get added to the spec. @astleychen @KuoE0 are ok with that? Do you think there should be a masking specific CSS WG resolution? Let me know please.

**Comment by astleychen** [comment]
Yes, it's reasonable to have a consistent design with background-repeat property. There is no need for other resolution. Thanks.
